{
  "services-auth-personal-representative": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/health/check",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "IDENTITY_SERVER_CLIENT_ID": "@island.is/clients/auth-api",
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        },
        "XROAD_NATIONAL_REGISTRY_ACTOR_TOKEN": "true",
        "XROAD_RSK_PROCURING_ACTOR_TOKEN": "true",
        "XROAD_NATIONAL_REGISTRY_SERVICE_PATH": {
          "dev": "IS-DEV/GOV/10001/SKRA-Protected/Einstaklingar-v1",
          "staging": "IS-TEST/GOV/6503760649/SKRA-Protected/Einstaklingar-v1",
          "prod": "IS/GOV/6503760649/SKRA-Protected/Einstaklingar-v1"
        },
        "XROAD_NATIONAL_REGISTRY_REDIS_NODES": {
          "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
          "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
          "prod": "[\"clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379\"]"
        },
        "XROAD_RSK_PROCURING_REDIS_NODES": {
          "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
          "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
          "prod": "[\"clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379\"]"
        },
        "COMPANY_REGISTRY_XROAD_PROVIDER_ID": {
          "dev": "IS-DEV/GOV/10006/Skatturinn/ft-v1",
          "staging": "IS-TEST/GOV/5402696029/Skatturinn/ft-v1",
          "prod": "IS/GOV/5402696029/Skatturinn/ft-v1"
        },
        "COMPANY_REGISTRY_REDIS_NODES": {
          "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
          "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
          "prod": "[\"clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379\"]"
        },
        "SYSLUMENN_HOST": {
          "dev": "https://api.syslumenn.is/staging",
          "staging": "https://api.syslumenn.is/staging",
          "prod": "https://api.syslumenn.is/api"
        },
        "SYSLUMENN_TIMEOUT": "3000",
        "ZENDESK_CONTACT_FORM_SUBDOMAIN": {
          "prod": "digitaliceland",
          "staging": "digitaliceland",
          "dev": "digitaliceland"
        }
      },
      "features": {},
      "name": "services-auth-personal-representative",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "ZENDESK_CONTACT_FORM_EMAIL": "/k8s/api/ZENDESK_CONTACT_FORM_EMAIL",
        "ZENDESK_CONTACT_FORM_TOKEN": "/k8s/api/ZENDESK_CONTACT_FORM_TOKEN",
        "ZENDESK_WEBHOOK_SECRET_GENERAL_MANDATE": "/k8s/services-auth/ZENDESK_WEBHOOK_SECRET_GENERAL_MANDATE",
        "IDENTITY_SERVER_CLIENT_SECRET": "/k8s/services-auth/IDENTITY_SERVER_CLIENT_SECRET",
        "SYSLUMENN_USERNAME": "/k8s/services-auth/SYSLUMENN_USERNAME",
        "SYSLUMENN_PASSWORD": "/k8s/services-auth/SYSLUMENN_PASSWORD"
      },
      "ingress": {
        "primary": {
          "host": {
            "dev": "personal-representative-xrd.internal.dev01.devland.is",
            "staging": "personal-representative-xrd.internal.staging01.devland.is",
            "prod": "personal-representative-xrd.internal.innskra.island.is"
          },
          "paths": [
            "/"
          ],
          "public": false
        }
      },
      "namespace": "personal-representative",
      "serviceAccountEnabled": false,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "400m",
          "memory": "512Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "256Mi"
        }
      },
      "xroadConfig": [
        {
          "config": {
            "env": {
              "XROAD_BASE_PATH": {
                "prod": "http://securityserver.island.is"
              },
              "XROAD_BASE_PATH_WITH_ENV": {
                "staging": "http://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "http://securityserver.island.is/r1/IS"
              },
              "XROAD_TLS_BASE_PATH": {
                "dev": "https://securityserver.dev01.devland.is",
                "staging": "https://securityserver.staging01.devland.is",
                "prod": "https://securityserver.island.is"
              },
              "XROAD_TLS_BASE_PATH_WITH_ENV": {
                "dev": "https://securityserver.dev01.devland.is/r1/IS-DEV",
                "staging": "https://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "https://securityserver.island.is/r1/IS"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_CLIENT_ID": {
                "dev": "IS-DEV/GOV/10000/island-is-client",
                "staging": "IS-TEST/GOV/5501692829/island-is-client",
                "prod": "IS/GOV/5501692829/island-is-client"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_RSK_PROCURING_PATH": {
                "dev": "IS-DEV/GOV/10006/Skatturinn/relationships-v1",
                "staging": "IS-TEST/GOV/5402696029/Skatturinn/relationships-v1",
                "prod": "IS/GOV/5402696029/Skatturinn/relationships-v1"
              }
            }
          }
        }
      ],
      "files": [],
      "volumes": [],
      "image": "services-auth-personal-representative",
      "postgres": {
        "name": "servicesauth",
        "username": "servicesauth",
        "passwordSecret": "/k8s/servicesauth/DB_PASSWORD"
      },
      "replicaCount": {
        "default": 2,
        "min": 2,
        "max": 10
      }
    }
  }
}