# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  env:
    AWS_REGION: 'eu-west-1'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'

web:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx-external
      cert-manager.io/cluster-issuer: devland-is-letsencrypt-dns01

    hosts:
      - host: beta.dev01.devland.is
        paths: ['/']
    tls:
      - secretName: web-tls
        hosts:
          - beta.dev01.devland.is

search-indexer-service:
  serviceAccount:
    name: 'search-indexer'
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::013313053092:role/search-indexer'
  secrets:
    CONTENTFUL_ACCESS_TOKEN: '/k8s/search-indexer/CONTENTFUL_ACCESS_TOKEN'
  env:
    APPLICATION_URL: 'http://search-indexer-service'
    ELASTIC_NODE: 'https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com'
    ELASTIC_INDEX: 'island-is'
    CONTENTFUL_SPACE: '8k0h54kbe6bj'
    CONTENTFUL_ENVIRONMENT: 'master'
    CONTENTFUL_HOST: 'preview.contentful.com'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-external
      cert-manager.io/cluster-issuer: devland-is-letsencrypt-dns01
    hosts:
      - host: search-indexer-service.dev01.devland.is
        paths: ['/']
    tls:
      - secretName: search-indexer-service-tls
        hosts:
          - search-indexer-service.dev01.devland.is

  initContainer:
    env:
      ELASTIC_NODE: 'https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com'
      APPLICATION_URL: 'http://search-indexer-service'
      ELASTIC_INDEX: 'island-is'
      S3_BUCKET: 'dev-es-custom-packages'
api:
  secrets:
    CONTENTFUL_ACCESS_TOKEN: '/k8s/api/CONTENTFUL_ACCESS_TOKEN'
  env:
    ELASTIC_NODE: 'https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com'
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      kubernetes.io/ingress.class: nginx-external
      cert-manager.io/cluster-issuer: devland-is-letsencrypt-dns01
    hosts:
      - host: beta.dev01.devland.is
        paths: ['/api']
    tls:
      - secretName: web-tls
        hosts:
          - beta.dev01.devland.is
