# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    tag: latest_master

web:
  namespace: islandis
  env:
    API_URL: 'http://web-api'

api:
  namespace: islandis
  secrets:
    CONTENTFUL_ACCESS_TOKEN: '/k8s/api/CONTENTFUL_ACCESS_TOKEN'
  env:
    PORT: 3333

search-indexer-service:
  namespace: search-indexer
  secrets:
    CONTENTFUL_ACCESS_TOKEN: "/k8s/search-indexer/CONTENTFUL_ACCESS_TOKEN"
  environment:
    APPLICATION_URL: "http://search-indexer-service"
    ELASTIC_NODE: "https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com"
    ELASTIC_INDEX: "island-is"
    CONTENTFUL_SPACE: "8k0h54kbe6bj"
    CONTENTFUL_ENVIRONMENT: "master"
    CONTENTFUL_HOST: "preview.contentful.com"
    S3_BUCKET: "prod-es-custom-packages"

  migration_script: /webapp/bin/migrate.js
  serviceAccount:
    create: true
    name: 'search-indexer'

