name: 'Format and linter'
description: 'Action to format and linter'
inputs:
  max-jobs: 
    description: 'Max jobs'
    default: '2'
  push-changes:
    description: 'Should push changes'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Format
      env:
        RUN_WRITE: ${{ inputs.push-changes }}
      shell: bash
      run: |
        if [ "$RUN_WRITE" != "true" ]; then
          ./scripts/ci/20_check-formatting.sh "check"
        else
          ./infra/scripts/ci/git-check-dirty.sh "/" "nx format:write" "dirtybot"
        fi
    - name: Get Linter Jobs
      id: get-linter-jobs
      env:
        DISABLE_CHUNKS: 'true'
        DISABLE_GROUPING: 'true'
        DISABLE_PROBLEMATIC: 'true'
      shell: bash
      run: |
        set -euo pipefail
        CHUNKS="$(./scripts/ci/generate-chunks.sh lint)"
        if [[ "$CHUNKS" != "[]" ]]; then
          echo "AFFECTED_PROJECTS={\"projects\":$CHUNKS}" >> "$GITHUB_OUTPUT"
        fi
    - name: Lint
      if: ${{ env.AFFECTED_PROJECTS != '' }}
      env:
        MAX_JOBS: ${{ inputs.max-jobs }}
      shell: bash
      run: |
        ./scripts/ci/run-in-parallel-native.sh lint
