{
  "judicial-system-message-handler": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "SQS_QUEUE_NAME": "sqs-judicial-system",
        "SQS_DEAD_LETTER_QUEUE_NAME": "sqs-judicial-system-dlq",
        "SQS_REGION": "eu-west-1"
      },
      "features": {},
      "name": "judicial-system-message-handler",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "BACKEND_ACCESS_TOKEN": "/k8s/judicial-system/BACKEND_ACCESS_TOKEN"
      },
      "ingress": {},
      "namespace": "judicial-system",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "memory": "256Mi",
          "cpu": "200m"
        },
        "requests": {
          "memory": "128Mi",
          "cpu": "100m"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "accountName": "judicial-system-message-handler",
      "image": "judicial-system-message-handler",
      "cmds": "node",
      "args": [
        "--no-experimental-fetch",
        "main.js"
      ]
    }
  }
}