version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: ../../../scripts/ci/Dockerfile.test
      args:
        DB_NAME: db_documents
        APP: services-documents
    networks:
      - local
    depends_on:
      - db_documents
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=db_documents
    volumes:
      - ../../..:/code

  db_documents:
    ports: []
