version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - automerge
      - dependencies
    reviewers:
      - island-is/core

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - automerge
      - dependencies
    reviewers:
      - island-is/core

  - package-ecosystem: npm
    directory: /.github/actions/
    schedule:
      interval: daily
    labels:
      - automerge
      - dependencies
    reviewers:
      - island-is/core
