nodeLinker: node-modules
nmMode: hardlinks-local
yarnPath: .yarn/releases/yarn-3.2.3.cjs
defaultSemverRangePrefix: ''
packageExtensions:
  "@keyv/redis@*":
    peerDependencies:
      "ioredis": "5.3.2"
  "bull@*":
    peerDependencies:
      "ioredis": "5.3.2"
  "cache-manager-ioredis-yet@*":
    peerDependencies:
      "ioredis": "5.3.2"