compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

enableTelemetry: false

httpRetry: 3

httpTimeout: 60000

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

networkConcurrency: 8

nmMode: hardlinks-local

nodeLinker: node-modules

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs
