compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

networkConcurrency: 16

nmMode: hardlinks-local

nodeLinker: node-modules

preferInteractive: false

yarnPath: .yarn/releases/yarn-4.6.0.cjs

packageExtensions:
  "bull@4.10.4":
    dependencies:
      ioredis: "5.3.2"
  "cache-manager-ioredis-yet@1.1.0":
    dependencies:
      ioredis: "5.3.2"