services:
  api:
    build:
      context: ./
      dockerfile: scripts/ci/Dockerfile
      target: src
      args:
        NODE_IMAGE_TAG: 20.15.0-alpine3.20
        APP: api
        APP_HOME: apps/api
        APP_DIST_HOME: dist/apps/api
    container_name: api
    environment:
      SERVERSIDE_FEATURES_ON:
      APPLICATION_SYSTEM_API_URL: http://localhost:9613
      USER_NOTIFICATION_API_URL: http://localhost:9314
      ICELANDIC_NAMES_REGISTRY_BACKEND_URL: http://localhost:9823
      AIR_DISCOUNT_SCHEME_BACKEND_URL: http://localhost:9298
      AIR_DISCOUNT_SCHEME_FRONTEND_HOSTNAME: loftbru.dev01.devland.is
      FILE_STORAGE_UPLOAD_BUCKET: island-is-dev-upload-api
      AUTH_PUBLIC_API_URL: https://identity-server.dev01.devland.is/api
      CONTENTFUL_HOST: preview.contentful.com
      CONTACT_US_EMAIL: s@kogk.is
      ZENDESK_CONTACT_FORM_SUBDOMAIN: stjanilofts
      TELL_US_A_STORY_EMAIL: s@kogk.is
      SEND_FROM_EMAIL: development@island.is
      USER_PROFILE_CLIENT_URL: http://localhost:9166
      FILE_DOWNLOAD_BUCKET: island-is-dev-download-cache-api
      SERVICE_DOCUMENTS_BASEPATH: http://localhost:9163
      DOWNLOAD_SERVICE_BASE_PATH: https://api.dev01.devland.is
      ENDORSEMENT_SYSTEM_BASE_API_URL: http://localhost:9673
      REGULATIONS_ADMIN_URL: http://localhost:9686
      IDENTITY_SERVER_CLIENT_ID: "@island.is/clients/api"
      AIR_DISCOUNT_SCHEME_CLIENT_TIMEOUT: 20000
      XROAD_NATIONAL_REGISTRY_TIMEOUT: 20000
      XROAD_PROPERTIES_TIMEOUT: 35000
      SYSLUMENN_TIMEOUT: 40000
      XROAD_DRIVING_LICENSE_BOOK_TIMEOUT: 20000
      XROAD_FINANCES_TIMEOUT: 20000
      XROAD_CHARGE_FJS_V2_TIMEOUT: 20000
      AUTH_DELEGATION_API_URL: http://web-services-auth-delegation-api.identity-server-delegation.svc.cluster.local
      IDENTITY_SERVER_ISSUER_URL: https://identity-server.dev01.devland.is
      MUNICIPALITIES_FINANCIAL_AID_BACKEND_URL: http://web-financial-aid-backend
      FINANCIAL_STATEMENTS_INAO_BASE_PATH: https://dev-re.crm4.dynamics.com/api/data/v9.1
      FINANCIAL_STATEMENTS_INAO_ISSUER: https://login.microsoftonline.com/05a20268-aaea-4bb5-bb78-960b0462185e/v2.0
      FINANCIAL_STATEMENTS_INAO_SCOPE: https://dev-re.crm4.dynamics.com/.default
      FINANCIAL_STATEMENTS_INAO_TOKEN_ENDPOINT: https://login.microsoftonline.com/05a20268-aaea-4bb5-bb78-960b0462185e/oauth2/v2.0/token
      ELECTRONIC_REGISTRATION_STATISTICS_API_URL: https://api-staging.thinglysing.is/business/tolfraedi
      FORM_SYSTEM_API_BASE_PATH: https://profun.island.is/umsoknarkerfi
      CONSULTATION_PORTAL_CLIENT_BASE_PATH: https://samradapi-test.devland.is
      FISKISTOFA_ZENTER_CLIENT_ID: 1114
      HSN_WEB_FORM_ID: 1dimJFHLFYtnhoYEA3JxRK
      SESSIONS_API_URL: http://localhost:9354
      AUTH_ADMIN_API_PATH: https://identity-server.dev01.devland.is/backend
      AUTH_ADMIN_API_PATHS: "{\"development\":\"https://identity-server.dev01.devland.is/backend\"}"
      AUTH_IDS_API_URL: https://identity-server.dev01.devland.is
      HUNTING_LICENSE_PASS_TEMPLATE_ID: 1da72d52-a93a-4d0f-8463-1933a2bd210b
      XROAD_RSK_PROCURING_SCOPE: "[\"@rsk.is/prokura\",\"@rsk.is/prokura:admin\"]"
      UNIVERSITY_GATEWAY_API_URL: http://localhost:9470
      WATSON_ASSISTANT_CHAT_FEEDBACK_DB_NAME: island-is-assistant-feedback
      XROAD_ADR_MACHINE_LICENSE_PATH: IS-DEV/GOV/10013/Vinnueftirlitid-Protected/rettindi-token-v1
      XROAD_COURT_BANKRUPTCY_CERT_PATH: IS-DEV/GOV/10019/Domstolasyslan/JusticePortal-v1
      XROAD_HUNTING_LICENSE_PATH: IS-DEV/GOV/10009/Umhverfisstofnun-Protected/api
      XROAD_FIREARM_LICENSE_PATH: IS-DEV/GOV/10005/Logreglan-Protected/island-api-v1
      XROAD_DISABILITY_LICENSE_PATH: IS-DEV/GOV/10008/TR-Protected/oryrki-v1
      XROAD_BASE_PATH: http://localhost:9388
      XROAD_BASE_PATH_WITH_ENV: http://localhost:9388/r1/IS-DEV
      XROAD_TLS_BASE_PATH: https://securityserver.dev01.devland.is
      XROAD_TLS_BASE_PATH_WITH_ENV: https://securityserver.dev01.devland.is/r1/IS-DEV
      XROAD_CLIENT_ID: IS-DEV/GOV/10000/island-is-client
      XROAD_HEALTH_DIRECTORATE_PATH: IS-DEV/GOV/10015/EmbaettiLandlaeknis-Protected/landlaeknir
      XROAD_HEALTH_INSURANCE_WSDLURL: https://test-huld.sjukra.is/islandrg?wsdl
      XROAD_HEALTH_INSURANCE_ID: IS-DEV/GOV/10007/SJUKRA-Protected
      XROAD_HEALTH_INSURANCE_MY_PAGES_PATH: IS-DEV/GOV/10007/SJUKRA-Protected/minarsidur
      XROAD_INTELLECTUAL_PROPERTIES_PATH: IS-DEV/GOV/10030/WebAPI-Public/HUG-webAPI
      XROAD_INNA_PATH: IS-DEV/GOV/10066/MMS-Protected/inna-v1
      XROAD_VMST_API_PATH: /VMST-ParentalLeave-Protected/ParentalLeaveApplication-v1
      XROAD_VMST_MEMBER_CODE: 10003
      XROAD_DRIVING_LICENSE_PATH: r1/IS-DEV/GOV/10005/Logreglan-Protected/RafraentOkuskirteini-v1
      XROAD_DRIVING_LICENSE_V2_PATH: r1/IS-DEV/GOV/10005/Logreglan-Protected/RafraentOkuskirteini-v2
      XROAD_DRIVING_LICENSE_V4_PATH: r1/IS-DEV/GOV/10005/Logreglan-Protected/Okuskirteini-v4
      XROAD_DRIVING_LICENSE_V5_PATH: r1/IS-DEV/GOV/10005/Logreglan-Protected/Okuskirteini-v5
      XROAD_PAYMENT_PROVIDER_ID: IS-DEV/GOV/10021/FJS-Public
      XROAD_PAYMENT_BASE_CALLBACK_URL: XROAD:/IS-DEV/GOV/10000/island-is/application-callback-v2/application-payment/
      XROAD_PAYMENT_ADDITION_CALLBACK_URL: /
      XROAD_DISTRICT_COMMISSIONERS_P_CARD_PATH: IS-DEV/GOV/10016/Syslumenn-Protected/IslandMinarSidur
      XROAD_DISTRICT_COMMISSIONERS_LICENSES_PATH: IS-DEV/GOV/10016/Syslumenn-Protected/RettindiIslandis
      XROAD_FINANCES_PATH: IS-DEV/GOV/10021/FJS-Public/financeIsland
      XROAD_FINANCES_V2_PATH: IS-DEV/GOV/10021/FJS-Public/financeServicesFJS_v2
      XROAD_HMS_LOANS_PATH: IS-DEV/GOV/10033/HMS-Protected/libra-v1
      XROAD_HMS_HOUSING_BENEFITS_PATH: IS-DEV/GOV/10033/HMS-Protected/husbot-v1
      XROAD_MMS_LICENSE_SERVICE_ID: IS-DEV/GOV/10066/MMS-Protected/license-api-v1
      XROAD_MMS_GRADE_SERVICE_ID: IS-DEV/GOV/10066/MMS-Protected/grade-api-v1
      XROAD_NATIONAL_REGISTRY_SERVICE_PATH: IS-DEV/GOV/10001/SKRA-Protected/Einstaklingar-v1
      XROAD_TJODSKRA_API_PATH: /SKRA-Protected/Einstaklingar-v1
      XROAD_TJODSKRA_MEMBER_CODE: 10001
      XROAD_PROPERTIES_SERVICE_V2_PATH: IS-DEV/GOV/10033/HMS-Protected/Fasteignir-v1
      XROAD_PAYMENT_SCHEDULE_PATH: IS-DEV/GOV/10021/FJS-Public/paymentSchedule_v1
      XROAD_CRIMINAL_RECORD_PATH: r1/IS-DEV/GOV/10005/Logreglan-Protected/Sakavottord-PDF-v2
      COMPANY_REGISTRY_XROAD_PROVIDER_ID: IS-DEV/GOV/10006/Skatturinn/ft-v1
      FISHING_LICENSE_XROAD_PROVIDER_ID: IS-DEV/GOV/10012/Fiskistofa-Protected/veidileyfi-v1
      XROAD_FINANCIAL_AID_BACKEND_PATH: IS-DEV/MUN/10023/samband-sveitarfelaga/financial-aid-backend
      XROAD_VEHICLES_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Mitt-Svaedi-V1
      XROAD_VEHICLES_MILEAGE_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-Mileagereading-V1
      XROAD_PASSPORT_LICENSE_PATH: IS-DEV/GOV/10001/SKRA-Cloud-Protected/Forskraning-V1
      XROAD_VEHICLE_SERVICE_FJS_V1_PATH: IS-DEV/GOV/10021/FJS-Public/VehicleServiceFJS_v1
      XROAD_VEHICLE_CODETABLES_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-Codetables-V1
      XROAD_VEHICLE_INFOLOCKS_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-Infolocks-V1
      XROAD_VEHICLE_OPERATORS_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-Operators-V3
      XROAD_VEHICLE_OWNER_CHANGE_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-Ownerchange-V2
      XROAD_VEHICLE_PLATE_ORDERING_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-PlateOrdering-V1
      XROAD_VEHICLE_PLATE_RENEWAL_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-PlateOwnership-V1
      XROAD_VEHICLE_PRINTING_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Vehicle-Printing-V1
      XROAD_DIGITAL_TACHOGRAPH_DRIVERS_CARD_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Okuritar-V1
      XROAD_CHARGE_FJS_V2_PATH: IS-DEV/GOV/10021/FJS-Public/chargeFJS_v2
      XROAD_ENERGY_FUNDS_PATH: IS-DEV/GOV/10021/FJS-Public/ElectricCarSubSidyService_v1
      XROAD_UNIVERSITY_OF_AKUREYRI_PATH: IS-DEV/EDU/10054/UNAK-Protected/brautskraning-v1
      XROAD_AGRICULTURAL_UNIVERSITY_OF_ICELAND_PATH: IS-DEV/EDU/10056/LBHI-Protected/brautskraning-v1
      XROAD_BIFROST_UNIVERSITY_PATH: IS-DEV/EDU/10057/Bifrost-Protected/brautskraning-v1
      XROAD_HOLAR_UNIVERSITY_PATH: IS-DEV/EDU/10055/Holar-Protected/brautskraning-v1
      XROAD_ICELAND_UNIVERSITY_OF_THE_ARTS_PATH: IS-DEV/EDU/10049/LHI-Protected/brautskraning-v1
      XROAD_UNIVERSITY_OF_ICELAND_PATH: IS-DEV/EDU/10010/HI-Protected/brautskraning-v1
      XROAD_WORK_MACHINE_LICENSE_PATH: IS-DEV/GOV/10013/Vinnueftirlitid-Protected/vinnuvelar-token
      XROAD_ICELANDIC_GOVERNMENT_INSTITUTION_VACANCIES_PATH: IS-DEV/GOV/10021/FJS-Protected/recruitment-v1
      XROAD_RSK_PROCURING_PATH: IS-DEV/GOV/10006/Skatturinn/relationships-v1
      NATIONAL_REGISTRY_B2C_CLIENT_ID: b464afdd-056b-406d-b650-6d41733cfeb7
      NATIONAL_REGISTRY_B2C_ENDPOINT: https://skraidentitydev.b2clogin.com/skraidentitydev.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token
      NATIONAL_REGISTRY_B2C_SCOPE: https://skraidentitydev.onmicrosoft.com/midlun/.default
      NATIONAL_REGISTRY_B2C_PATH: IS-DEV/GOV/10001/SKRA-Cloud-Protected/Midlun-v1
      XROAD_AIRCRAFT_REGISTRY_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/Loftfaraskra-V1
      XROAD_HOUSING_BENEFIT_CALCULATOR_PATH: IS-DEV/GOV/10033/HMS-Protected/calc-v1
      XROAD_SHIP_REGISTRY_PATH: IS-DEV/GOV/10017/Samgongustofa-Protected/skipaskra-V1
      XROAD_DIRECTORATE_OF_IMMIGRATION_PATH: IS-DEV/GOV/10011/UTL-Protected/Utl-Umsokn-v1
      XROAD_SIGNATURE_COLLECTION_PATH: IS-DEV/GOV/10001/SKRA-Cloud-Protected/Medmaeli-v1
      XROAD_TR_PATH: IS-DEV/GOV/10008/TR-Protected/external-v1
      XROAD_OFFICIAL_JOURNAL_PATH: IS-DEV/GOV/10014/DMR-Protected/official-journal
      XROAD_JUDICIAL_SYSTEM_SP_PATH: IS-DEV/GOV/10014/Rettarvorslugatt-Private/judicial-system-mailbox-api
      XROAD_OFFICIAL_JOURNAL_APPLICATION_PATH: IS-DEV/GOV/10014/DMR-Protected/official-journal-application
      XROAD_MMS_FRIGG_PATH: IS-DEV/GOV/10066/MMS-Protected/frigg-form-service
      XROAD_HEALTH_DIRECTORATE_ORGAN_DONATION_PATH: IS-DEV/GOV/10015/EmbaettiLandlaeknis-Protected/organ-donation-v1
      XROAD_HEALTH_DIRECTORATE_VACCINATION_PATH: IS-DEV/GOV/10015/EmbaettiLandlaeknis-Protected/vaccination-v1
      XROAD_WORK_ACCIDENT_PATH: IS-DEV/GOV/10013/Vinnueftirlitid-Protected/slysaskraning-token
      PROD_MODE: true
      PORT: 9456
      IP: 0.0.0.0
    ports:
      - 9456:9456
    command: "yarn nx serve api"
    working_dir: /app
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./.yarn:/app/.yarn
      - ./yarn.lock:/app/yarn.lock
      - ./package.json:/app/package.json
    networks:
      - local
    privileged: true
    healthcheck:
      test:
        - CMD
        - wget
        - "--spider"
        - "--quiet"
        - http://localhost:9456/liveness
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s
  consultation-portal:
    build:
      context: ./
      dockerfile: scripts/ci/Dockerfile
      target: src
      args:
        NODE_IMAGE_TAG: 20.15.0-alpine3.20
        APP: consultation-portal
        APP_HOME: apps/consultation-portal
        APP_DIST_HOME: dist/apps/consultation-portal
    container_name: consultation-portal
    environment:
      SERVERSIDE_FEATURES_ON:
      CODE_OWNER: Advania
      BASEPATH: /consultation-portal
      ENVIRONMENT: local
      API_URL: http://api:9456
      IDENTITY_SERVER_ISSUER_DOMAIN: identity-server.dev01.devland.is
      NEXTAUTH_URL: http://api:4200/samradsgatt/api/auth
      BACKEND_DL_URL: https://samradapi-test.devland.is/api/Documents/
      PROD_MODE: true
      IP: 0.0.0.0
    ports:
      - 4200:4200
    command: "yarn nx serve consultation-portal"
    working_dir: /app
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./.yarn:/app/.yarn
      - ./yarn.lock:/app/yarn.lock
      - ./package.json:/app/package.json
    networks:
      - local
    privileged: true
    depends_on:
      api:
        condition: service_healthy
networks:
  local:
