{
  "user-notification-cleanup-worker": {
    "serviceDef": {
      "liveness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {},
      "features": {},
      "name": "user-notification-cleanup-worker",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY"
      },
      "ingress": {},
      "namespace": "user-notification",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "memory": "256Mi",
          "cpu": "200m"
        },
        "requests": {
          "memory": "128Mi",
          "cpu": "100m"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "image": "services-user-notification",
      "accountName": "user-notification-cleanup-worker",
      "cmds": "node",
      "args": [
        "--no-experimental-fetch",
        "main.js",
        "--job=cleanup"
      ],
      "postgres": {
        "name": "user_notification",
        "username": "user_notification",
        "passwordSecret": "/k8s/user-notification/DB_PASSWORD"
      },
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          }
        ],
        "postgres": {
          "name": "user_notification",
          "username": "user_notification",
          "passwordSecret": "/k8s/user-notification/DB_PASSWORD"
        }
      },
      "extraAttributes": {
        "dev": {
          "schedule": "@hourly"
        },
        "staging": {
          "schedule": "@midnight"
        },
        "prod": {
          "schedule": "@midnight"
        }
      }
    }
  }
}