openapi: 3.0.0
info:
  title: Reference backend
  description: This is provided as a reference to implement other backends.
  version: "1.0"
  contact: {}
tags:
  - name: reference
    description: ""
servers: []
components:
  schemas:
    Liveness:
      type: object
      properties:
        ok:
          type: boolean
      required:
        - ok
    Version:
      type: object
      properties:
        version:
          type: string
      required:
        - version
    ResourceDto:
      type: object
      properties:
        nationalId:
          type: string
      required:
        - nationalId
    Resource:
      type: object
      properties:
        id:
          type: string
        nationalId:
          type: string
        created:
          format: date-time
          type: string
        modified:
          format: date-time
          type: string
      required:
        - id
        - nationalId
        - created
        - modified
paths:
  /liveness:
    get:
      operationId: InfraController_liveness
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Liveness"
      tags:
        &a1
        - internal
  /version:
    get:
      operationId: InfraController_version
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Version"
      tags: *a1
  /resource:
    post:
      operationId: ResourceController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResourceDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
      tags:
        &a2
        - resource
  "/resource/{nationalId}":
    get:
      operationId: ResourceController_findOne
      parameters:
        - name: nationalId
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Resource"
      tags: *a2
