{
  "github-actions-cache": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/health",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "REDIS_NODES": "clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379"
      },
      "features": {},
      "name": "github-actions-cache",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY"
      },
      "ingress": {
        "primary": {
          "host": {
            "dev": [
              "cache"
            ],
            "staging": [
              ""
            ],
            "prod": [
              "",
              ""
            ]
          },
          "paths": [
            "/"
          ],
          "extraAnnotations": {
            "dev": {
              "nginx.ingress.kubernetes.io/enable-global-auth": "false"
            }
          },
          "public": true
        }
      },
      "namespace": "github-actions-cache",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "400m",
          "memory": "512Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "256Mi"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "accountName": "github-actions-cache",
      "cmds": "node",
      "args": [
        "--tls-min-v1.0",
        "--no-experimental-fetch",
        "main.js"
      ],
      "replicaCount": {
        "min": 3,
        "max": 8,
        "default": 5
      }
    }
  }
}