service:
  name: 'github-actions-cache'
  args:
    - '--tls-min-v1.0'
    - '--no-experimental-fetch'
    - 'main.js'
  command:
    - 'node'
  enabled: true
  env:
    LOG_LEVEL: 'info'
    NODE_OPTIONS: '--max-old-space-size=460'
    REDIS_NODES: 'clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/health'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 90
        nginxRequestsIrate: 5
      replicas:
        max: 8
        min: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/github-actions-cache'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
        nginx.ingress.kubernetes.io/service-upstream: 'true'
      hosts:
        - host: 'cache.dev01.devland.is'
          paths:
            - '/'
  namespace: 'github-actions-cache'
  podDisruptionBudget:
    maxUnavailable: 1
  podSecurityContext:
    fsGroup: 65534
  pvcs: []
  replicaCount:
    default: 5
    max: 8
    min: 3
  resources:
    limits:
      cpu: '400m'
      memory: '512Mi'
    requests:
      cpu: '100m'
      memory: '256Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::013313053092:role/github-actions-cache'
    create: true
    name: 'github-actions-cache'
