name: 'Determine if testing everything'
description: 'Sets a TEST_EVERYTHING env for later use'

runs:
  using: 'composite'
  steps:
    - name: Set Test Everything flag
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" && "${{ contains(github.event.pull_request.labels.*.name, 'test everything') }}" == "true" ]]; then
          echo "TEST_EVERYTHING=true" >> "$GITHUB_ENV"
        else
          echo "TEST_EVERYTHING=false" >> "$GITHUB_ENV"
        fi
