version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: ../../../scripts/Dockerfile-test
      args:
        DB_NAME: db_gjafakort_application
        APP: gjafakort-application
    networks:
      - local
    depends_on:
      - db_gjafakort_application
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=db_gjafakort_application
    volumes:
      - ../../..:/code

  db_gjafakort_application:
    ports: []
