version: '3.3'

services:
  db_gjafakort_application:
    image: public.ecr.aws/bitnami/postgresql:11.12.0
    container_name: db_gjafakort_application
    networks:
      - local
    environment:
      - POSTGRES_PASSWORD=XjFsvIrGyCCrdE
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DEV_DB_USER=dev_db
      - DEV_DB_PASS=dev_db
      - DEV_DB_NAME=dev_db
    volumes:
      - ./bin/startup.sql:/docker-entrypoint-initdb.d/startup.sql
    ports:
      - 5432:5432

  redis_cluster:
    container_name: redis_cluster
    image: grokzen/redis-cluster:5.0.6
    privileged: true
    sysctls:
      net.core.somaxconn: '511'
    environment:
      - IP=0.0.0.0
    ports:
      - '7000-7005:7000-7005'

  localstack:
    container_name: localstack
    image: public.ecr.aws/s4w6t4b6/localstack/localstack:0.11.1
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - SERVICES=sns:4575,sqs:4576
    ports:
      - '4575:4575'
      - '4576:4576'

networks:
  local:
