# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

gjafakort-api:
  environment:
    auth_audience: 'ferdagjof.island.is'
    cache_time_to_live: 86400
    ferdalag_url: 'https://island-prod-dot-itb-gagnagrunnur-dev.appspot.com'
    rsk_url: 'https://thjonusta.rsk.is/api'
    saml_entry_point: 'https://innskraning.island.is/?id=ferdagjof.prod'
    sentry_dsn: 'https://91d3faa6cc0545a9971ea989eaa48fb9@o406638.ingest.sentry.io/5274533'
    yay_url: 'https://serviceapi.yay.is'

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'ferdagjof-island-is-letsencrypt-dns01'
    hosts:
      - host: 'ferdagjof.island.is'
        paths:
          - '/api'
    tls:
      - hosts: ['ferdagjof.island.is']
        secretName: 'gjafakort-web-tls'

gjafakort-web:
  environment:
    sentry_auth_token: 'https://7d11c5b6d23449659e812f4cb0b711d3@o406638.ingest.sentry.io/5274507'
    sentry_org: 'island_is'
    sentry_project: 'gjafakort-web'

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'ferdagjof-island-is-letsencrypt-dns01'
    hosts:
      - host: 'ferdagjof.island.is'
        paths:
          - '/'
    tls:
      - hosts: ['ferdagjof.island.is']
        secretName: 'gjafakort-web-tls'

gjafakort-application:
  postgres:
    host: 'prod-vidspyrna-aurora.cluster-cneim47t7wpr.eu-west-1.rds.amazonaws.com'
    name: 'gjafakort_application'
    username: 'gjafakort_application'
    sentry_dsn: 'https://91d3faa6cc0545a9971ea989eaa48fb9@o406638.ingest.sentry.io/5274533'

  ingress:
    enabled: false
  podSecurityContext:
    fsGroup: 65534
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::251502586493:role/gjafakort-sqs-producer'
    create: true
    name: 'gjafakort-sqs-producer'

gjafakort-queue-listener:
  environment:
    ferdalag_url: 'https://island-prod-dot-itb-gagnagrunnur-dev.appspot.com'
    sentry_dsn: 'https://91d3faa6cc0545a9971ea989eaa48fb9@o406638.ingest.sentry.io/5274533'
    yay_url: 'https://serviceapi.yay.is'

  podSecurityContext:
    fsGroup: 65534
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::251502586493:role/gjafakort-sqs-consumer'
    create: true
    name: 'gjafakort-sqs-consumer'
