name: 'Prep Dependencies'
description: 'Install or restore steps and save to cache'
inputs:
  generated_files:
    required: false
    description: 'name of the generated files archive to cache'
    default: ${{ github.sha }}.tar.gz

runs:
  using: 'composite'
  steps:
    - name: Prepare generated files
      shell: bash
      run: |
        echo "generated files: ${{ inputs.generated_files }}"
        node ./scripts/ci/generate-files.mjs ${{ inputs.generated_files }}

    - name: Cache Generated files
      uses: runs-on/cache/save@v4
      with:
        path: |
          ${{ inputs.generated_files }}
        key: generated-files-${{ github.sha }}
