name: 'Prep Dependencies'
description: 'Makes sure all dependencies are installed and caches are restored (prereq for load-deps)'
inputs:
  cypress_cache_folder:
    required: true
  generated_files:
    required: true
outputs:
  random-number:
    description: 'Random number'
    value: ${{ steps.random-number-generator.outputs.random-number }}
  test_chunks:
    value: ${{ steps.build_info.outputs.TEST_CHUNKS }}
  e2e_chunks:
    value: ${{ steps.build_info.outputs.E2E_CHUNKS }}
  e2e_build_id:
    value: ${{ steps.build_info.outputs.BUILD_ID }}
  build_chunks:
    value: ${{ steps.build_info.outputs.BUILD_CHUNKS }}
  nx_base:
    value: ${{ steps.build_info.outputs.NX_BASE }}
  # cache_key:
  #   value: ${{ steps.set-cache-key.outputs.cache_key }}
  # yarn_cache_folder:
  #   value: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  cache_key:
    value: 'cool'
  yarn_cache_folder:
    value: 'beans'

runs:
  using: 'composite'
  steps:
    # - name: Corepack
    #   shell: bash
    #   run: |
    #     corepack enable && \
    #     corepack prepare --activate && \
    #     yarn --version && \
    #     yarn install --immutable

    # - name: Link pre-installed dependencies
    #   shell: bash
    #   run: |
    #     ln -s /home/runner/dependencies/node_modules $GITHUB_WORKSPACE/node_modules
    #     echo "NODE_PATH=/home/runner/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV

    # - name: Configure Yarn
    #   shell: bash
    #   run: |
    #     echo "nodeLinker: node-modules" >> .yarnrc.yml
    #     echo "enableGlobalCache: false" >> .yarnrc.yml
    #     yarn config set cacheFolder /home/runner/dependencies/.yarn/cache

    - name: Link pre-installed dependencies
      shell: bash
      run: |
        mkdir -p node_modules .yarn
        ln -sfn /home/runner/dependencies/node_modules/* node_modules/
        ln -sfn /home/runner/dependencies/.yarn .yarn
        echo "NODE_PATH=/home/runner/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV

    - name: Verify dependency setup
      shell: bash
      run: |
        yarn --version
        yarn why react  # Replace 'react' with a package you know is in your dependencies

    - name: Prepare generated files
      shell: bash
      run: |
        echo "generated files: ${{ inputs.generated_files }}"
        node ./scripts/ci/generate-files.mjs ${{ inputs.generated_files }}
        tar -xzvf ${{ inputs.generated_files }}

    - name: Cache Generated files
      uses: runs-on/cache/save@v4
      with:
        path: |
          ${{ inputs.generated_files }}
        key: generated-files-${{ github.sha }}

    - name: Derive appropriate SHAs
      uses: nrwl/nx-set-shas@v4

    - name: Gather branch info
      id: build_info
      shell: bash
      run: |
        export BASE=${{ env.NX_BASE }}
        export HEAD=${{ env.NX_HEAD }}

        echo "TEST_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh test)}"
        if [[ "$TEST_CHUNKS" != "[]" ]]; then
          echo TEST_CHUNKS="{\"projects\":$TEST_CHUNKS}" >> "$GITHUB_OUTPUT"
        fi

        echo "BUILD_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh build)}"
        if [[ "$BUILD_CHUNKS" != "[]" ]]; then
          echo BUILD_CHUNKS="{\"projects\":$BUILD_CHUNKS}" >> "$GITHUB_OUTPUT"
        fi


        echo "E2E_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh e2e-ci)}"
        if [[ "$E2E_CHUNKS" != "[]" ]]; then
          echo E2E_CHUNKS="{\"projects\":$E2E_CHUNKS}" >> "$GITHUB_OUTPUT"
        fi
        echo BUILD_ID="$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER-$(uuidgen)" >> "$GITHUB_OUTPUT"
        echo "NX_BASE=$BASE" >> "$GITHUB_OUTPUT"
