name: 'Get Cache Keys'
description: 'Action to get cache'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  enable-cache:
    description: 'Enable cache'
    default: ''
  cache-url:
    description: 'URL to cache to/from'
    default: 'https://cache.dev01.devland.is/'
  keys:
    description: 'Keys'
    default: 'false'
outputs:
  keys:
    description: 'Keys'
    value: ${{ steps.prepare.outputs._CACHE_KEYS }}
runs:
  using: 'composite'
  steps:
    - name: Debug inputs
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          console.log(JSON.stringify(inputs, null, 2))

    - name: Adding required env vars
      uses: actions/github-script@v7
      env:
        ACTIONS_CACHE_URL: ${{ inputs.cache-url }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env['ACTIONS_CACHE_URL'])
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
    - name: Get cache
      id: prepare
      shell: bash
      env:
        _CACHE_KEYS: ${{ inputs.keys }}
        ENABLE_CACHE: ${{ inputs.enable-cache }}
        NODE_OPTIONS: --max-old-space-size=8192
      run: |
        # This is because of a weird bug where Github would write as root to .cache
        export COREPACK_HOME=/github/home/.corepack-cache
        export CYPRESS_CACHE_FOLDER=/github/home/.cypress-cache
        echo "COREPACK_HOME=$COREPACK_HOME" >> $GITHUB_ENV
        echo "CYPRESS_CACHE_FOLDER=$CYPRESS_CACHE_FOLDER" >> $GITHUB_ENV
        cd scripts/ci/cache
        npx yarn install --immutable
        node cache-action.mjs
