name: 'Get Cache Keys'
description: 'Action to get cache'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  enable-cache:
    description: 'Enable cache'
    default: ''
  keys:
    description: 'Keys'
    default: 'false'
outputs:
  success:
    description: 'Success'
    value: ${{ steps.run-post-cache.outputs.success }}
  keys:
    description: 'Keys'
    value: ${{ steps.get-cache-keys.outputs._CACHE_KEYS }}
runs:
  using: 'composite'
  steps:
    - name: Adding required env vars
      uses: actions/github-script@v7
      env:
        github-token: ${{ inputs.GITHUB_TOKEN }}
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', 'https://cache.dev01.devland.is/')
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env['ACTIONS_RUNTIME_TOKEN'])
          core.exportVariable('ACTIONS_RUNTIME_URL', process.env['ACTIONS_RUNTIME_URL'])
    - name: Get cache
      id: prepare
      shell: bash
      env:
        ENABLE_CACHE: ${{ inputs.enable-cache }}
        YAML_FILE: ./.tmp-dynamic-cache/action.yml
      run: |
        cd scripts/ci/cache
        yarn install --immutable
        node cache-action.mjs
