name: 'Get Cache Keys'
description: 'Action to get cache'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  cache-url:
    description: 'Cache URL'
    default: 'https://cache.dev01.devland.is/'
  enable-cache:
    description: 'Enable cache'
    default: ''
  keys:
    description: 'Keys'
    default: 'false'
outputs:
  keys:
    description: 'Keys'
    value: ${{ steps.prepare.outputs._CACHE_KEYS }}
runs:
  using: 'composite'
  steps:
    - name: Adding required env vars
      shell: bash
      env:
        CACHE_URL: ${{ github.event.localrun && env.ACTIONS_CACHE_URL || inputs.cache-url }}
      run: |
        set -x
        echo "ACTIONS_CACHE_URL=$CACHE_URL" >>"$GITHUB_ENV"
        echo "ACTIONS_RUNTIME_TOKEN=$ACTIONS_RUNTIME_TOKEN" >>"$GITHUB_ENV"
        echo "ACTIONS_RUNTIME_URL=$ACTIONS_RUNTIME_URL" >>"$GITHUB_ENV"
    - name: Get cache
      id: prepare
      shell: bash
      env:
        _CACHE_KEYS: ${{ inputs.keys }}
        ENABLE_CACHE: ${{ inputs.enable-cache }}
        NODE_OPTIONS: --max-old-space-size=8192
      run: |
        # This is because of a weird bug where Github would write as root to .cache
        export COREPACK_HOME="$HOME/.corepack-cache"
        export CYPRESS_CACHE_FOLDER="$HOME/.cypress-cache"
        echo "COREPACK_HOME=$COREPACK_HOME" >> $GITHUB_ENV
        echo "CYPRESS_CACHE_FOLDER=$CYPRESS_CACHE_FOLDER" >> $GITHUB_ENV
        cd scripts/ci/cache
        npx yarn install --immutable
        node cache-action.mjs
