name: 'Get Cache Keys'
description: 'Action to get cache'
inputs:
  enable-cache:
    description: 'Enable cache'
    default: ''
  keys:
    description: 'Keys'
    default: 'false'
  cypress-path:
    description: 'Path to cypress'
    default: '/github/home/.cache/Cypress'
outputs:
  success:
    description: 'Success'
    value: ${{ steps.run-post-cache.outputs.success }}
  keys:
    description: 'Keys'
    value: ${{ steps.get-cache-keys.outputs._CACHE_KEYS }}
runs:
  using: 'composite'
  steps:
    - uses: cue-lang/setup-cue@v1.0.1
    - name: Get cache
      id: prepare
      shell: bash
      env:
        ENABLE_CACHE: ${{ inputs.enable-cache }}
        CYPRESS_PATH: ${{ inputs.cypress-path }}
        YAML_FILE: ./.tmp-dynamic-cache/action.yml
      run: |
        node --experimental-network-imports scripts/ci/cache/generate-cache-steps.mjs
    