{
  "air-discount-scheme-api": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "AUTH_AUDIENCE": {
          "staging": "loftbru.staging01.devland.is",
          "prod": "loftbru.island.is"
        },
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        },
        "ELASTIC_NODE": {
          "dev": "https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com",
          "staging": "https://vpc-search-q6hdtjcdlhkffyxvrnmzfwphuq.eu-west-1.es.amazonaws.com",
          "prod": "https://vpc-search-mw4w5c2m2g5edjrtvwbpzhkw24.eu-west-1.es.amazonaws.com"
        },
        "CONTENTFUL_HOST": {
          "dev": "preview.contentful.com",
          "staging": "cdn.contentful.com",
          "prod": "cdn.contentful.com"
        }
      },
      "features": {},
      "name": "air-discount-scheme-api",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "AUTH_JWT_SECRET": "/k8s/air-discount-scheme/api/AUTH_JWT_SECRET",
        "CONTENTFUL_ACCESS_TOKEN": "/k8s/air-discount-scheme/api/CONTENTFUL_ACCESS_TOKEN",
        "DEVELOPERS": "/k8s/air-discount-scheme/api/DEVELOPERS",
        "ADMINS": "/k8s/air-discount-scheme/api/ADMINS"
      },
      "ingress": {
        "primary": {
          "host": {
            "dev": [
              "loftbru",
              "loftbru-cf"
            ],
            "staging": [
              "loftbru",
              "loftbru-cf"
            ],
            "prod": [
              "loftbru"
            ]
          },
          "paths": [
            "/api/graphql"
          ],
          "public": true
        }
      },
      "namespace": "air-discount-scheme",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "400m",
          "memory": "512Mi"
        },
        "requests": {
          "cpu": "50m",
          "memory": "256Mi"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "accountName": "air-discount-scheme-api",
      "replicaCount": {
        "min": 2,
        "max": 10,
        "default": 2,
        "scalingMagicNumber": 20
      }
    }
  }
}