version: '3.3'

services:
  sut:
    image: ${SUT}
    networks:
      - local
    environment:
      - POSTGRES_PASSWORD=XjFsvIrGyCCrdE
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
