{
  "services-university-gateway-worker": {
    "serviceDef": {
      "liveness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "IDENTITY_SERVER_CLIENT_ID": "@island.is/clients/university-gateway",
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        }
      },
      "features": {},
      "name": "services-university-gateway-worker",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "IDENTITY_SERVER_CLIENT_SECRET": "/k8s/services-university-gateway/IDENTITY_SERVER_CLIENT_SECRET"
      },
      "ingress": {},
      "namespace": "services-university-gateway",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "200m",
          "memory": "384Mi"
        },
        "requests": {
          "cpu": "50m",
          "memory": "256Mi"
        }
      },
      "xroadConfig": [
        {
          "config": {
            "env": {
              "XROAD_BASE_PATH": {
                "prod": "http://securityserver.island.is"
              },
              "XROAD_BASE_PATH_WITH_ENV": {
                "staging": "http://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "http://securityserver.island.is/r1/IS"
              },
              "XROAD_TLS_BASE_PATH": {
                "dev": "https://securityserver.dev01.devland.is",
                "staging": "https://securityserver.staging01.devland.is",
                "prod": "https://securityserver.island.is"
              },
              "XROAD_TLS_BASE_PATH_WITH_ENV": {
                "dev": "https://securityserver.dev01.devland.is/r1/IS-DEV",
                "staging": "https://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "https://securityserver.island.is/r1/IS"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_CLIENT_ID": {
                "dev": "IS-DEV/GOV/10000/island-is-client",
                "staging": "IS-TEST/GOV/5501692829/island-is-client",
                "prod": "IS/GOV/5501692829/island-is-client"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_UNIVERSITY_GATEWAY_UNIVERSITY_OF_ICELAND_PATH": {
                "dev": "IS-DEV/EDU/10010/HI-Protected/umsoknir-v1",
                "staging": "IS-TEST/EDU/10010/HI-Protected/umsoknir-v1",
                "prod": "IS/EDU/6001692039/HI-Protected/umsoknir-v1"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_UNIVERSITY_GATEWAY_UNIVERSITY_OF_AKUREYRI_PATH": {
                "dev": "IS-DEV/EDU/10054/UNAK-Protected/umsoknir-v1",
                "staging": "IS-TEST/EDU/10054/UNAK-Protected/umsoknir-v1",
                "prod": "IS/EDU/5206871229/UNAK-Protected/umsoknir-v1"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_UNIVERSITY_GATEWAY_BIFROST_UNIVERSITY_PATH": {
                "dev": "IS-DEV/EDU/10057/Bifrost-Protected/umsoknir-v1",
                "staging": "IS-TEST/EDU/10057/Bifrost-Protected/umsoknir-v1",
                "prod": "IS/EDU/5502690239/Bifrost-Protected/umsoknir-v1"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_UNIVERSITY_GATEWAY_ICELAND_UNIVERSITY_OF_THE_ARTS_PATH": {
                "dev": "IS-DEV/EDU/10049/LHI-Protected/umsoknir-v1",
                "staging": "IS-TEST/EDU/10049/LHI-Protected/umsoknir-v1",
                "prod": "IS/EDU/4210984099/LHI-Protected/umsoknir-v1"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_UNIVERSITY_GATEWAY_AGRICULTURAL_UNIVERSITY_OF_ICELAND_PATH": {
                "dev": "IS-DEV/EDU/10056/LBHI-Protected/umsoknir-v1",
                "staging": "IS-TEST/EDU/10056/LBHI-Protected/umsoknir-v1",
                "prod": "IS/EDU/4112043590/LBHI-Protected/umsoknir-v1"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_UNIVERSITY_GATEWAY_HOLAR_UNIVERSITY_PATH": {
                "dev": "IS-DEV/EDU/10055/Holar-Protected/umsoknir-v1",
                "staging": "IS-TEST/EDU/10055/Holar-Protected/umsoknir-v1",
                "prod": "IS/EDU/5001694359/Holar-Protected/umsoknir-v1"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_UNIVERSITY_GATEWAY_REYKJAVIK_UNIVERSITY_PATH": {
                "dev": "IS-DEV/EDU/10062/RvkUni-Hvin-Protected/umsoknir-v1",
                "staging": "IS-TEST/EDU/5101054190/RvkUni-Hvin-Protected/umsoknir-v1",
                "prod": "IS/EDU/5101054190/RvkUni-Hvin-Protected/umsoknir-v1"
              }
            }
          }
        }
      ],
      "files": [],
      "volumes": [],
      "accountName": "services-university-gateway-worker",
      "image": "services-university-gateway",
      "cmds": "node",
      "redis": {},
      "args": [
        "main.js",
        "--job",
        "worker"
      ],
      "postgres": {
        "username": "services_university_gateway",
        "passwordSecret": "/k8s/services-university-gateway/DB_PASSWORD",
        "name": "services_university_gateway"
      },
      "extraAttributes": {
        "dev": {
          "schedule": "0 * * * *"
        },
        "staging": {
          "schedule": "0 2 * * *"
        },
        "prod": {
          "schedule": "0 * * * *"
        }
      }
    }
  }
}