apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gjafakort-queue-listener.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "gjafakort-queue-listener.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.default }}
  selector:
    matchLabels:
      {{- include "gjafakort-queue-listener.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gjafakort-queue-listener.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gjafakort-queue-listener.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7777
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            {{- with .Values.environment }}
            - name: YAY_URL
              value: {{ .yay_url }}
            - name: YAY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gjafakort-queue-listener
                  key: YAY_API_KEY
            - name: YAY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gjafakort-queue-listener
                  key: YAY_SECRET_KEY
            - name: FERDALAG_URL
              value: {{ .ferdalag_url }}
            - name: FERDALAG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gjafakort-queue-listener
                  key: FERDALAG_API_KEY
            - name: APPLICATION_URL
              value: {{ .application_url }}
            - name: SENTRY_DSN
              value: {{ .sentry_dsn }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
