name: 'Prepare docker dependencies'
description: 'If yarn.lock has changed we rebuild/push the dockerfile deps layer'
inputs:
  cache_repo:
    description: 'ECR layer cache repo'
    required: false
    default: docker-cache
  docker_registry:
    description: ''
    required: false
    default: 821090935708.dkr.ecr.eu-west-1.amazonaws.com
  aws_region:
    description: ''
    required: false
    default: eu-west-1
  s3_cache_bucket:
    description: ''
    required: true

outputs:
  cache_image:
    description: ''
    value: ${{ steps.set-cache-image.outputs.image }}
runs:
  using: 'composite'
  steps:
    - name: Calculate yarn.lock SHA
      shell: bash
      id: yarn-sha
      run: echo "sha=$(sha256sum yarn.lock | cut -d ' ' -f 1 | head -c 11)" >> $GITHUB_OUTPUT

    - name: Set cache image tag
      shell: bash
      id: cache-tag
      run: echo "tag=deps-${{ steps.yarn-sha.outputs.sha }}" >> $GITHUB_OUTPUT

    - name: Check if deps cache exists
      shell: bash
      id: check-deps-cache
      run: |
        if aws ecr describe-images --repository-name ${{ inputs.cache_repo }} --image-ids imageTag=${{ steps.cache-tag.outputs.tag }} &>/dev/null; then
          exists=true
        else
          exists=false
        fi
        echo "cache exists: $exists"
        echo "cache_exists=$exists" >> $GITHUB_OUTPUT
      continue-on-error: true

    - name: Build and push deps layer
      if: steps.check-deps-cache.outputs.cache_exists != 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./scripts/ci/Dockerfile
        tags: ${{ inputs.docker_registry }}/${{ inputs.cache_repo }}:${{ steps.cache-tag.outputs.tag }}
        cache-from: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ inputs.aws_region }},bucket=${{ inputs.s3_cache_bucket }}
        cache-to: type=s3,blobs_prefix=cache/${{ github.repository }}/,manifests_prefix=cache/${{ github.repository }}/,region=${{ inputs.aws_region }},bucket=${{ inputs.s3_cache_bucket }},mode=max

    - name: Set cache image
      shell: bash
      id: set-cache-image
      run: echo "image=${{ inputs.docker_registry }}/${{ inputs.cache_repo }}:${{ steps.cache-tag.outputs.tag }}" >> $GITHUB_OUTPUT
