name: 'Load Dependencies'
description: 'Fetch and extract generated files. Depends on the `setup-yarn` action.'

runs:
  using: 'composite'
  steps:
    - name: Prep env
      shell: bash
      id: prep
      env:
        GENERATED_FILES: ${{ github.workspace }}/dist/codegen/${{ github.event.localrun && 'codegen' || github.sha }}.tar.gz
      run: |
        echo "generated files: ${GENERATED_FILES}"
        echo "GENERATED_FILES=${GENERATED_FILES}" | tee -a "$GITHUB_ENV" "$GITHUB_OUTPUT"
        mkdir -p "$(dirname "${GENERATED_FILES}")"

    - name: Restore generated files
      uses: runs-on/cache/restore@v4
      id: restore-codegen-cache
      with:
        path: |
          ${{ steps.prep.outputs.GENERATED_FILES }}
        key: generated-files-${{ steps.prep.outputs.GENERATED_FILES }}

    - name: Prepare generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        tar -xzvf "${GENERATED_FILES}" || echo "Skipping untaring local file tarball"
        node ./scripts/ci/generate-files.mjs "${GENERATED_FILES}"

    - name: Extract generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        tar -xzvf "${GENERATED_FILES}"

    - name: Cache Generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit != 'true' }}
      uses: runs-on/cache/save@v4
      with:
        path: |
          ${{ steps.prep.outputs.GENERATED_FILES }}
        key: generated-files-${{ steps.prep.outputs.GENERATED_FILES }}
