name: 'Load Dependencies'
description: 'Fetch and extract generated files. Depends on the `install` action.'

runs:
  using: 'composite'
  steps:
    - name: INFO
      shell: bash
      run: |
        echo "generated files: ${GENERATED_FILES}"

    - name: Restore generated files
      uses: runs-on/cache/restore@v4
      id: restore-codegen-cache
      with:
        path: |
          ${GENERATED_FILES}
        key: generated-files-${{ github.sha }}

    - name: Prepare generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        node ./scripts/ci/generate-files.mjs "${GENERATED_FILES}"

    - name: Extract generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        tar -xzvf "${GENERATED_FILES}"

    - name: Cache Generated files
      if: ${{ steps.restore-codegen-cache.outputs.cache-hit != 'true' }}
      uses: runs-on/cache/save@v4
      with:
        path: |
          ${GENERATED_FILES}
        key: generated-files-${{ github.sha }}
