name: islandis-shared
services:
  redis-cluster:
    container_name: redis_cluster
    image: docker.io/grokzen/redis-cluster:6.0.16
    privileged: true
    environment:
      - IP=0.0.0.0
    ports:
      - '7010-7015:7000-7005'
