{
  "services-documents": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/readiness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        }
      },
      "features": {},
      "name": "services-documents",
      "grantNamespaces": [
        "islandis",
        "application-system"
      ],
      "grantNamespacesEnabled": true,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY"
      },
      "ingress": {},
      "namespace": "services-documents",
      "serviceAccountEnabled": false,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "memory": "256Mi",
          "cpu": "200m"
        },
        "requests": {
          "memory": "128Mi",
          "cpu": "100m"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "image": "services-documents",
      "postgres": {
        "username": "services_documents",
        "passwordSecret": "/k8s/services-documents/DB_PASSWORD",
        "name": "services_documents"
      },
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          }
        ],
        "postgres": {
          "username": "services_documents",
          "passwordSecret": "/k8s/services-documents/DB_PASSWORD",
          "name": "services_documents"
        }
      }
    }
  }
}