version: '3.3'

services:
  db_application_system:
    ports:
      - 5432:5432

  redis-cluster:
    container_name: redis_cluster
    image: public.ecr.aws/bitnami/redis-cluster:5.0.12
    privileged: true
    sysctls:
      net.core.somaxconn: '511'
    environment:
      - IP=0.0.0.0
    ports:
      - '7000-7005:7000-7005'
