version: '3.3'

services:
  sut:
    build:
      context: .
      dockerfile: ../../../scripts/ci/Dockerfile.test
      args:
        DB_NAME: db_application_system
        APP: application-system-api
    networks:
      - local
    depends_on:
      - db_application_system
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=db_application_system
    volumes:
      - ../../..:/code

  db_application_system:
    ports: []
