air-discount-scheme-api:
  enabled: true
  env:
    AUTH_AUDIENCE: loftbru.island.is
    BACKEND_URL: 'http://web-air-discount-scheme-backend'
    CONTENTFUL_HOST: cdn.contentful.com
    ELASTIC_NODE: 'https://vpc-search-mw4w5c2m2g5edjrtvwbpzhkw24.eu-west-1.es.amazonaws.com'
    SAML_ENTRY_POINT: 'https://innskraning.island.is/?id=ads.prod'
    SENTRY_DSN: 'https://d10d7fc22f18413d97e73fab76910f07@o406638.ingest.sentry.io/5399531'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      path: /liveness
    readiness:
      path: /liveness
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-api
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: nginx-external-alb
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: loftbru.island.is
          paths:
            - /api
  namespace: air-discount-scheme
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 2
    max: 10
    min: 2
  secrets:
    ADMINS: /k8s/air-discount-scheme/api/ADMINS
    AUTH_JWT_SECRET: /k8s/air-discount-scheme/api/AUTH_JWT_SECRET
    CONFIGCAT_SDK_KEY: /k8s/configcat/CONFIGCAT_SDK_KEY
    CONTENTFUL_ACCESS_TOKEN: /k8s/air-discount-scheme/api/CONTENTFUL_ACCESS_TOKEN
    DEVELOPERS: /k8s/air-discount-scheme/api/DEVELOPERS
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::251502586493:role/air-discount-scheme-api'
    create: true
    name: air-discount-scheme-api
air-discount-scheme-backend:
  enabled: true
  env:
    DB_HOST: prod-vidspyrna-aurora.cluster-cneim47t7wpr.eu-west-1.rds.amazonaws.com
    DB_NAME: air_discount_scheme_backend
    DB_USER: air_discount_scheme_backend
    ENVIRONMENT: prod
    REDIS_URL_NODE_01: >-
      clustercfg.general-redis-cluster-group.whakos.euw1.cache.amazonaws.com:6379
    SENTRY_DSN: 'https://d10d7fc22f18413d97e73fab76910f07@o406638.ingest.sentry.io/5399531'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      path: /liveness
    readiness:
      path: /liveness
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-backend
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: nginx-external-alb
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: loftbru.island.is
          paths:
            - /api/swagger
            - /api/public
  initContainer:
    containers:
      - args:
          - sequelize-cli
          - 'db:migrate'
        command:
          - npx
    env:
      DB_HOST: prod-vidspyrna-aurora.cluster-cneim47t7wpr.eu-west-1.rds.amazonaws.com
      DB_NAME: air_discount_scheme_backend
      DB_USER: air_discount_scheme_backend
    secrets:
      DB_PASS: /k8s/air-discount-scheme/backend/DB_PASSWORD
  namespace: air-discount-scheme
  replicaCount:
    default: 2
    max: 10
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: /k8s/configcat/CONFIGCAT_SDK_KEY
    DB_PASS: /k8s/air-discount-scheme/backend/DB_PASSWORD
    ERNIR_API_KEY: /k8s/air-discount-scheme/backend/ERNIR_API_KEY
    ICELANDAIR_API_KEY: /k8s/air-discount-scheme/backend/ICELANDAIR_API_KEY
    NATIONAL_REGISTRY_PASSWORD: /k8s/air-discount-scheme/backend/NATIONAL_REGISTRY_PASSWORD
    NORLANDAIR_API_KEY: /k8s/air-discount-scheme/backend/NORLANDAIR_API_KEY
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
air-discount-scheme-web:
  enabled: true
  env:
    API_URL: 'http://web-air-discount-scheme-api'
    SENTRY_DSN: 'https://d10d7fc22f18413d97e73fab76910f07@o406638.ingest.sentry.io/5399531'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      path: /liveness
    readiness:
      path: /readiness
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-web
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: nginx-external-alb
        nginx.ingress.kubernetes.io/configuration-snippet: >-
          rewrite /$ https://island.is/loftbru; rewrite /en$
          https://island.is/en/lower-airfares-for-residents-in-rural-areas;
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: loftbru.island.is
          paths:
            - /
  namespace: air-discount-scheme
  replicaCount:
    default: 2
    max: 10
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: /k8s/configcat/CONFIGCAT_SDK_KEY
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
global:
  env:
    AWS_REGION: eu-west-1
    PORT: '3333'
    name: prod
  image:
    tag: latest_master
  initContainer:
    env:
      AWS_REGION: eu-west-1

