apiVersion: v1
kind: Service
metadata:
  name: {{ include "air-discount-scheme-backend.fullname" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "air-discount-scheme-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4242
      protocol: TCP
      name: http
  selector:
    {{- include "air-discount-scheme-backend.selectorLabels" . | nindent 4 }}
