{
  "services-sessions-worker": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        },
        "REDIS_USE_SSL": "true"
      },
      "features": {},
      "name": "services-sessions-worker",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY"
      },
      "ingress": {},
      "namespace": "services-sessions",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "400m",
          "memory": "512Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "256Mi"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "image": "services-sessions",
      "redis": {},
      "accountName": "sessions-worker",
      "cmds": "node",
      "args": [
        "main.js",
        "--job=worker"
      ],
      "postgres": {
        "extensions": [
          "uuid-ossp"
        ],
        "readOnly": false,
        "username": "services_sessions",
        "passwordSecret": "/k8s/services-sessions/DB_PASSWORD",
        "name": "services_sessions"
      },
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          }
        ],
        "postgres": {
          "extensions": [
            "uuid-ossp"
          ],
          "readOnly": false,
          "username": "services_sessions",
          "passwordSecret": "/k8s/services-sessions/DB_PASSWORD",
          "name": "services_sessions"
        }
      }
    }
  }
}