{
  "service-portal-api": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/readiness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "SERVICE_PORTAL_BASE_URL": {
          "dev": "https://beta.dev01.devland.is/minarsidur",
          "staging": "https://beta.staging01.devland.is/minarsidur",
          "prod": "https://island.is/minarsidur",
          "local": "http://localhost:4200/minarsidur"
        },
        "EMAIL_REGION": "eu-west-1",
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        },
        "NOVA_ACCEPT_UNAUTHORIZED": {
          "dev": "true",
          "staging": "false",
          "prod": "false"
        },
        "AUTH_DELEGATION_API_URL": {
          "dev": "http://web-services-auth-delegation-api.identity-server-delegation.svc.cluster.local",
          "staging": "http://web-services-auth-delegation-api.identity-server-delegation.svc.cluster.local",
          "prod": "https://auth-delegation-api.internal.innskra.island.is"
        },
        "AUTH_DELEGATION_MACHINE_CLIENT_SCOPE": "[\"@island.is/auth/delegations/index:system\"]"
      },
      "features": {},
      "name": "service-portal-api",
      "grantNamespaces": [
        "nginx-ingress-internal",
        "islandis",
        "user-notification",
        "identity-server",
        "application-system"
      ],
      "grantNamespacesEnabled": true,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "NOVA_URL": "/k8s/service-portal-api/NOVA_URL",
        "NOVA_PASSWORD": "/k8s/gjafakort/NOVA_PASSWORD",
        "NOVA_USERNAME": "/k8s/gjafakort/NOVA_USERNAME",
        "EMAIL_FROM": "/k8s/service-portal/api/EMAIL_FROM",
        "EMAIL_FROM_NAME": "/k8s/service-portal/api/EMAIL_FROM_NAME",
        "EMAIL_REPLY_TO": "/k8s/service-portal/api/EMAIL_REPLY_TO",
        "EMAIL_REPLY_TO_NAME": "/k8s/service-portal/api/EMAIL_REPLY_TO_NAME",
        "ISLYKILL_SERVICE_PASSPHRASE": "/k8s/api/ISLYKILL_SERVICE_PASSPHRASE",
        "ISLYKILL_SERVICE_BASEPATH": "/k8s/api/ISLYKILL_SERVICE_BASEPATH",
        "IDENTITY_SERVER_CLIENT_ID": "/k8s/service-portal/api/SERVICE_PORTAL_API_CLIENT_ID",
        "IDENTITY_SERVER_CLIENT_SECRET": "/k8s/service-portal/api/SERVICE_PORTAL_API_CLIENT_SECRET",
        "NATIONAL_REGISTRY_B2C_CLIENT_SECRET": "/k8s/api/NATIONAL_REGISTRY_B2C_CLIENT_SECRET"
      },
      "ingress": {
        "internal": {
          "host": {
            "dev": "service-portal-api",
            "staging": "service-portal-api",
            "prod": "service-portal-api"
          },
          "paths": [
            "/"
          ],
          "public": false
        }
      },
      "namespace": "service-portal",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "800m",
          "memory": "1024Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "512Mi"
        }
      },
      "xroadConfig": [
        {
          "config": {
            "env": {
              "XROAD_BASE_PATH": {
                "prod": "http://securityserver.island.is"
              },
              "XROAD_BASE_PATH_WITH_ENV": {
                "staging": "http://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "http://securityserver.island.is/r1/IS"
              },
              "XROAD_TLS_BASE_PATH": {
                "dev": "https://securityserver.dev01.devland.is",
                "staging": "https://securityserver.staging01.devland.is",
                "prod": "https://securityserver.island.is"
              },
              "XROAD_TLS_BASE_PATH_WITH_ENV": {
                "dev": "https://securityserver.dev01.devland.is/r1/IS-DEV",
                "staging": "https://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "https://securityserver.island.is/r1/IS"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_CLIENT_ID": {
                "dev": "IS-DEV/GOV/10000/island-is-client",
                "staging": "IS-TEST/GOV/5501692829/island-is-client",
                "prod": "IS/GOV/5501692829/island-is-client"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "NATIONAL_REGISTRY_B2C_CLIENT_ID": {
                "dev": "b464afdd-056b-406d-b650-6d41733cfeb7",
                "staging": "ca128c23-b43c-443d-bade-ec5a146a933f",
                "prod": "2304d7ca-7ed3-4188-8b6d-e1b7e0e3df7f"
              },
              "NATIONAL_REGISTRY_B2C_ENDPOINT": {
                "dev": "https://skraidentitydev.b2clogin.com/skraidentitydev.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token",
                "staging": "https://skraidentitydev.b2clogin.com/skraidentitystaging.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token",
                "prod": "https://skraidentity.b2clogin.com/skraidentity.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token"
              },
              "NATIONAL_REGISTRY_B2C_SCOPE": {
                "dev": "https://skraidentitydev.onmicrosoft.com/midlun/.default",
                "staging": "https://skraidentitystaging.onmicrosoft.com/midlun/.default",
                "prod": "https://skraidentity.onmicrosoft.com/midlun/.default"
              },
              "NATIONAL_REGISTRY_B2C_PATH": {
                "dev": "IS-DEV/GOV/10001/SKRA-Cloud-Protected/Midlun-v1",
                "staging": "IS-TEST/GOV/6503760649/SKRA-Cloud-Protected/Midlun-v1",
                "prod": "IS/GOV/6503760649/SKRA-Cloud-Protected/Midlun-v1"
              }
            }
          }
        }
      ],
      "files": [
        {
          "filename": "islyklar.p12",
          "env": "ISLYKILL_CERT"
        }
      ],
      "volumes": [],
      "image": "services-user-profile",
      "accountName": "service-portal-api",
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          }
        ],
        "postgres": {
          "username": "service_portal_api",
          "passwordSecret": "/k8s/service-portal-api/DB_PASSWORD",
          "name": "service_portal_api"
        }
      },
      "replicaCount": {
        "default": 2,
        "max": 30,
        "min": 2
      },
      "postgres": {
        "username": "service_portal_api",
        "passwordSecret": "/k8s/service-portal-api/DB_PASSWORD",
        "name": "service_portal_api"
      }
    }
  }
}