{
  "endorsement-system-api": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "EMAIL_REGION": "eu-west-1",
        "EMAIL_FROM_NAME": {
          "dev": "devland.is",
          "staging": "devland.is",
          "prod": "island.is"
        },
        "EMAIL_FROM_ADDRESS": {
          "dev": "development@island.is",
          "staging": "development@island.is",
          "prod": "noreply@island.is"
        },
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        },
        "IDENTITY_SERVER_CLIENT_ID": "@island.is/clients/endorsement",
        "ENDORSEMENT_SYSTEM_EXPORTS_BUCKET_NAME": {
          "dev": "island-is-dev-exports-endorsement-system",
          "staging": "island-is-staging-exports-endorsement-system",
          "prod": "island-is-prod-exports-endorsement-system"
        }
      },
      "features": {},
      "name": "endorsement-system-api",
      "grantNamespaces": [
        "islandis",
        "application-system"
      ],
      "grantNamespacesEnabled": true,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "IDENTITY_SERVER_CLIENT_SECRET": "/k8s/endorsement-system-api/IDS-shared-secret",
        "NATIONAL_REGISTRY_B2C_CLIENT_SECRET": "/k8s/api/NATIONAL_REGISTRY_B2C_CLIENT_SECRET"
      },
      "ingress": {},
      "namespace": "endorsement-system",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "memory": "256Mi",
          "cpu": "200m"
        },
        "requests": {
          "memory": "128Mi",
          "cpu": "100m"
        }
      },
      "xroadConfig": [
        {
          "config": {
            "env": {
              "XROAD_BASE_PATH": {
                "prod": "http://securityserver.island.is"
              },
              "XROAD_BASE_PATH_WITH_ENV": {
                "staging": "http://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "http://securityserver.island.is/r1/IS"
              },
              "XROAD_TLS_BASE_PATH": {
                "dev": "https://securityserver.dev01.devland.is",
                "staging": "https://securityserver.staging01.devland.is",
                "prod": "https://securityserver.island.is"
              },
              "XROAD_TLS_BASE_PATH_WITH_ENV": {
                "dev": "https://securityserver.dev01.devland.is/r1/IS-DEV",
                "staging": "https://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "https://securityserver.island.is/r1/IS"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_CLIENT_ID": {
                "dev": "IS-DEV/GOV/10000/island-is-client",
                "staging": "IS-TEST/GOV/5501692829/island-is-client",
                "prod": "IS/GOV/5501692829/island-is-client"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_NATIONAL_REGISTRY_SERVICE_PATH": {
                "dev": "IS-DEV/GOV/10001/SKRA-Protected/Einstaklingar-v1",
                "staging": "IS-TEST/GOV/6503760649/SKRA-Protected/Einstaklingar-v1",
                "prod": "IS/GOV/6503760649/SKRA-Protected/Einstaklingar-v1"
              },
              "XROAD_NATIONAL_REGISTRY_REDIS_NODES": {
                "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
                "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
                "prod": "[\"clustercfg.general-redis-cluster-group.whakos.euw1.cache.amazonaws.com:6379\"]"
              },
              "XROAD_TJODSKRA_API_PATH": "/SKRA-Protected/Einstaklingar-v1",
              "XROAD_TJODSKRA_MEMBER_CODE": {
                "prod": "6503760649",
                "dev": "10001",
                "staging": "6503760649"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "NATIONAL_REGISTRY_B2C_CLIENT_ID": {
                "dev": "b464afdd-056b-406d-b650-6d41733cfeb7",
                "staging": "ca128c23-b43c-443d-bade-ec5a146a933f",
                "prod": "2304d7ca-7ed3-4188-8b6d-e1b7e0e3df7f"
              },
              "NATIONAL_REGISTRY_B2C_ENDPOINT": {
                "dev": "https://skraidentitydev.b2clogin.com/skraidentitydev.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token",
                "staging": "https://skraidentitydev.b2clogin.com/skraidentitystaging.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token",
                "prod": "https://skraidentity.b2clogin.com/skraidentity.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token"
              },
              "NATIONAL_REGISTRY_B2C_SCOPE": {
                "dev": "https://skraidentitydev.onmicrosoft.com/midlun/.default",
                "staging": "https://skraidentitystaging.onmicrosoft.com/midlun/.default",
                "prod": "https://skraidentity.onmicrosoft.com/midlun/.default"
              },
              "NATIONAL_REGISTRY_B2C_PATH": {
                "dev": "IS-DEV/GOV/10001/SKRA-Cloud-Protected/Midlun-v1",
                "staging": "IS-TEST/GOV/6503760649/SKRA-Cloud-Protected/Midlun-v1",
                "prod": "IS/GOV/6503760649/SKRA-Cloud-Protected/Midlun-v1"
              }
            }
          }
        }
      ],
      "files": [],
      "volumes": [],
      "image": "services-endorsements-api",
      "accountName": "endorsement-system-api",
      "cmds": "node",
      "args": [
        "--tls-min-v1.0",
        "--no-experimental-fetch",
        "main.js"
      ],
      "postgres": {
        "name": "services_endorsements_api",
        "username": "services_endorsements_api",
        "passwordSecret": "/k8s/services-endorsements-api/DB_PASSWORD"
      },
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          }
        ],
        "postgres": {
          "name": "services_endorsements_api",
          "username": "services_endorsements_api",
          "passwordSecret": "/k8s/services-endorsements-api/DB_PASSWORD"
        }
      }
    }
  }
}