{
  "services-auth-ids-api": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/health/check",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "IDENTITY_SERVER_CLIENT_ID": "@island.is/clients/auth-api",
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        },
        "PASSKEY_CORE_MAX_AGE_DAYS": "365",
        "PUBLIC_URL": {
          "dev": "https://identity-server.dev01.devland.is/api",
          "staging": "https://identity-server.staging01.devland.is/api",
          "prod": "https://innskra.island.is/api"
        },
        "USER_PROFILE_CLIENT_URL": {
          "dev": "http://web-service-portal-api.service-portal.svc.cluster.local",
          "staging": "http://web-service-portal-api.service-portal.svc.cluster.local",
          "prod": "https://service-portal-api.internal.island.is"
        },
        "USER_PROFILE_CLIENT_SCOPE": "[\"@island.is/user-profile:read\"]",
        "XROAD_NATIONAL_REGISTRY_SERVICE_PATH": {
          "dev": "IS-DEV/GOV/10001/SKRA-Protected/Einstaklingar-v1",
          "staging": "IS-TEST/GOV/6503760649/SKRA-Protected/Einstaklingar-v1",
          "prod": "IS/GOV/6503760649/SKRA-Protected/Einstaklingar-v1"
        },
        "XROAD_NATIONAL_REGISTRY_REDIS_NODES": {
          "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
          "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
          "prod": "[\"clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379\"]"
        },
        "COMPANY_REGISTRY_REDIS_NODES": {
          "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
          "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
          "prod": "[\"clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379\"]"
        },
        "XROAD_RSK_PROCURING_REDIS_NODES": {
          "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
          "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
          "prod": "[\"clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379\"]"
        },
        "COMPANY_REGISTRY_XROAD_PROVIDER_ID": {
          "dev": "IS-DEV/GOV/10006/Skatturinn/ft-v1",
          "staging": "IS-TEST/GOV/5402696029/Skatturinn/ft-v1",
          "prod": "IS/GOV/5402696029/Skatturinn/ft-v1"
        },
        "XROAD_TJODSKRA_API_PATH": "/SKRA-Protected/Einstaklingar-v1",
        "XROAD_TJODSKRA_MEMBER_CODE": {
          "prod": "6503760649",
          "dev": "10001",
          "staging": "6503760649"
        },
        "NOVA_ACCEPT_UNAUTHORIZED": {
          "dev": "true",
          "staging": "false",
          "prod": "false"
        },
        "PASSKEY_CORE_RP_ID": "island.is",
        "PASSKEY_CORE_RP_NAME": "Island.is",
        "PASSKEY_CORE_CHALLENGE_TTL_MS": "120000",
        "REDIS_NODES": {
          "dev": "[\"clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379\"]",
          "staging": "[\"clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379\"]",
          "prod": "[\"clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379\"]"
        },
        "PASSKEY_CORE_ALLOWED_ORIGINS": "[\"https://island.is\",\"android:apk-key-hash:JgPeo_F6KYk-ngRa26tO2SsAtMiTBQCc7WtSgN-jRX0\",\"android:apk-key-hash:EsLTUu5kaY7XPmMl2f7nbq4amu-PNzdYu3FecNf90wU\"]",
        "SYSLUMENN_HOST": {
          "dev": "https://api.syslumenn.is/staging",
          "staging": "https://api.syslumenn.is/staging",
          "prod": "https://api.syslumenn.is/api"
        },
        "SYSLUMENN_TIMEOUT": "3000"
      },
      "features": {},
      "name": "services-auth-ids-api",
      "grantNamespaces": [
        "nginx-ingress-external",
        "user-notification"
      ],
      "grantNamespacesEnabled": true,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "IDENTITY_SERVER_CLIENT_SECRET": "/k8s/services-auth/IDENTITY_SERVER_CLIENT_SECRET",
        "NOVA_URL": "/k8s/services-auth/NOVA_URL",
        "NOVA_USERNAME": "/k8s/services-auth/NOVA_USERNAME",
        "NOVA_PASSWORD": "/k8s/services-auth/NOVA_PASSWORD",
        "NATIONAL_REGISTRY_B2C_CLIENT_SECRET": "/k8s/services-auth/NATIONAL_REGISTRY_B2C_CLIENT_SECRET",
        "SYSLUMENN_USERNAME": "/k8s/services-auth/SYSLUMENN_USERNAME",
        "SYSLUMENN_PASSWORD": "/k8s/services-auth/SYSLUMENN_PASSWORD"
      },
      "ingress": {},
      "namespace": "identity-server",
      "serviceAccountEnabled": false,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "800m",
          "memory": "768Mi"
        },
        "requests": {
          "cpu": "400m",
          "memory": "512Mi"
        }
      },
      "xroadConfig": [
        {
          "config": {
            "env": {
              "XROAD_BASE_PATH": {
                "prod": "http://securityserver.island.is"
              },
              "XROAD_BASE_PATH_WITH_ENV": {
                "staging": "http://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "http://securityserver.island.is/r1/IS"
              },
              "XROAD_TLS_BASE_PATH": {
                "dev": "https://securityserver.dev01.devland.is",
                "staging": "https://securityserver.staging01.devland.is",
                "prod": "https://securityserver.island.is"
              },
              "XROAD_TLS_BASE_PATH_WITH_ENV": {
                "dev": "https://securityserver.dev01.devland.is/r1/IS-DEV",
                "staging": "https://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "https://securityserver.island.is/r1/IS"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_CLIENT_ID": {
                "dev": "IS-DEV/GOV/10000/island-is-client",
                "staging": "IS-TEST/GOV/5501692829/island-is-client",
                "prod": "IS/GOV/5501692829/island-is-client"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_RSK_PROCURING_PATH": {
                "dev": "IS-DEV/GOV/10006/Skatturinn/relationships-v1",
                "staging": "IS-TEST/GOV/5402696029/Skatturinn/relationships-v1",
                "prod": "IS/GOV/5402696029/Skatturinn/relationships-v1"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "NATIONAL_REGISTRY_B2C_CLIENT_ID": {
                "dev": "6cf94113-d326-4e4d-b97c-1fea12d2f5e1",
                "staging": "6cf94113-d326-4e4d-b97c-1fea12d2f5e1",
                "prod": "8271bbc2-d8de-480f-8540-ea43fc40b7ae"
              },
              "NATIONAL_REGISTRY_B2C_ENDPOINT": {
                "dev": "https://skraidentitydev.b2clogin.com/skraidentitydev.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token",
                "staging": "https://skraidentitydev.b2clogin.com/skraidentitydev.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token",
                "prod": "https://skraidentity.b2clogin.com/skraidentity.onmicrosoft.com/b2c_1_midlun_flow/oauth2/v2.0/token"
              },
              "NATIONAL_REGISTRY_B2C_SCOPE": {
                "dev": "https://skraidentitydev.onmicrosoft.com/midlun/.default",
                "staging": "https://skraidentitydev.onmicrosoft.com/midlun/.default",
                "prod": "https://skraidentity.onmicrosoft.com/midlun/.default"
              },
              "NATIONAL_REGISTRY_B2C_PATH": {
                "dev": "IS-DEV/GOV/10001/SKRA-Cloud-Protected/Midlun-v1",
                "staging": "IS-TEST/GOV/10001/SKRA-Cloud-Protected/Midlun-v1",
                "prod": "IS/GOV/6503760649/SKRA-Cloud-Protected/Midlun-v1"
              }
            }
          }
        }
      ],
      "files": [],
      "volumes": [],
      "image": "services-auth-ids-api",
      "postgres": {
        "name": "servicesauth",
        "extensions": [
          "uuid-ossp"
        ],
        "username": "servicesauth",
        "passwordSecret": "/k8s/servicesauth/DB_PASSWORD"
      },
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          },
          {
            "name": "seed",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:seed:all"
            ]
          }
        ],
        "postgres": {
          "name": "servicesauth",
          "extensions": [
            "uuid-ossp"
          ],
          "username": "servicesauth",
          "passwordSecret": "/k8s/servicesauth/DB_PASSWORD"
        }
      },
      "replicaCount": {
        "default": 2,
        "min": 2,
        "max": 15
      }
    }
  }
}