# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    tag: latest_master

air-discount-scheme-api:
  namespace: air-discount-scheme
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-api
  env:
    BACKEND_URL: "http://web-air-discount-scheme-backend"
  secrets:
    AUTH_JWT_SECRET: "/k8s/air-discount-scheme/api/AUTH_JWT_SECRET"
  healthCheck:
    livenessPath: /liveness
  service:
    targetPort: 4242

air-discount-scheme-web:
  namespace: air-discount-scheme
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-web
  env:
  service:
    targetPort: 4200

air-discount-scheme-backend:
  namespace: air-discount-scheme
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-backend
  initContainer:
    create: true
    command: ["npx"]
    args: ["sequelize-cli", "db:migrate"]
  env:
  secrets:
    DB_PASS: '/k8s/air-discount-scheme/backend/DB_PASSWORD'
  initContainer:
    secrets:
      DB_PASS: '/k8s/air-discount-scheme/backend/DB_PASSWORD'
  healthCheck:
    livenessPath: /liveness
  service:
    targetPort: 4248
