# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  env:
    name: 'prod'
    AWS_REGION: 'eu-west-1'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'

air-discount-scheme-api:
  env:

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'air-discount-scheme-island-is-letsencrypt-dns01'
    hosts:
      - host: 'ads.island.is'
        paths:
          - '/api'
    tls:
      - hosts: ['ads.island.is']
        secretName: 'air-discount-scheme-web-tls'

air-discount-scheme-web:
  env:

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'air-discount-scheme-island-is-letsencrypt-dns01'
    hosts:
      - host: 'ads.island.is'
        paths:
          - '/'
    tls:
      - hosts: ['ads.island.is']
        secretName: 'air-discount-scheme-web-tls'

air-discount-scheme-backend:
  env:
    DB_HOST: 'prod-vidspyrna-aurora.cluster-cneim47t7wpr.eu-west-1.rds.amazonaws.com'
    DB_NAME: 'air_discount_scheme_backend'
    DB_USERNAME: 'air_discount_scheme_backend'

  ingress:
    enabled: false
