# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

air-discount-scheme-api:
  environment:

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'devland-is-letsencrypt-dns01'
    hosts:
      - host: 'ads.dev01.devland.is'
        paths:
          - '/api'
    tls:
      - hosts: ['ads.dev01.devland.is']
        secretName: 'air-discount-scheme-web-tls'

air-discount-scheme-web:
  environment:

  ingress:
    annotations:
      cert-manager.io/cluster-issuer: 'devland-is-letsencrypt-dns01'
    hosts:
      - host: 'ads.dev01.devland.is'
        paths:
          - '/'
    tls:
      - hosts: ['ads.dev01.devland.is']
        secretName: 'air-discount-scheme-web-tls'

air-discount-scheme-backend:
  postgres:
    host: 'dev-vidspyrna-aurora-1.c6cxecmrvlpq.eu-west-1.rds.amazonaws.com'
    name: 'air_discount_scheme_backend'
    username: 'air_discount_scheme_backend'

  ingress:
    enabled: false

