{
  "search-indexer-service": {
    "serviceDef": {
      "liveness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "APPLICATION_URL": "http://search-indexer-service",
        "ELASTIC_NODE": {
          "dev": "https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com",
          "staging": "https://vpc-search-q6hdtjcdlhkffyxvrnmzfwphuq.eu-west-1.es.amazonaws.com",
          "prod": "https://vpc-search-mw4w5c2m2g5edjrtvwbpzhkw24.eu-west-1.es.amazonaws.com"
        },
        "ELASTIC_INDEX": "island-is",
        "CONTENTFUL_SPACE": "8k0h54kbe6bj",
        "CONTENTFUL_ENVIRONMENT": "master",
        "CONTENTFUL_HOST": {
          "dev": "preview.contentful.com",
          "staging": "cdn.contentful.com",
          "prod": "cdn.contentful.com"
        },
        "CONTENTFUL_ENTRY_FETCH_CHUNK_SIZE": {
          "dev": "40",
          "staging": "40",
          "prod": "40"
        },
        "AIR_DISCOUNT_SCHEME_FRONTEND_HOSTNAME": {
          "dev": "loftbru.dev01.devland.is",
          "staging": "loftbru.staging01.devland.is",
          "prod": "loftbru.island.is"
        }
      },
      "features": {},
      "name": "search-indexer-service",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "CONTENTFUL_ACCESS_TOKEN": "/k8s/search-indexer/CONTENTFUL_ACCESS_TOKEN",
        "API_CMS_SYNC_TOKEN": "/k8s/search-indexer/API_CMS_SYNC_TOKEN",
        "API_CMS_DELETION_TOKEN": "/k8s/search-indexer/API_CMS_DELETION_TOKEN",
        "APOLLO_BYPASS_CACHE_SECRET": "/k8s/api/APOLLO_BYPASS_CACHE_SECRET"
      },
      "ingress": {
        "primary": {
          "host": {
            "dev": "search-indexer-service",
            "staging": "search-indexer-service",
            "prod": "search-indexer-service.devland.is"
          },
          "paths": [
            "/"
          ],
          "extraAnnotations": {
            "dev": {
              "nginx.ingress.kubernetes.io/enable-global-auth": "false"
            },
            "staging": {
              "nginx.ingress.kubernetes.io/enable-global-auth": "false"
            },
            "prod": {}
          }
        }
      },
      "namespace": "search-indexer",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "requests": {
          "cpu": "400m",
          "memory": "3072Mi"
        },
        "limits": {
          "cpu": "800m",
          "memory": "4096Mi"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "image": "services-search-indexer",
      "accountName": "search-indexer",
      "initContainers": {
        "envs": {
          "APPLICATION_URL": "http://search-indexer-service",
          "ELASTIC_NODE": {
            "dev": "https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com",
            "staging": "https://vpc-search-q6hdtjcdlhkffyxvrnmzfwphuq.eu-west-1.es.amazonaws.com",
            "prod": "https://vpc-search-mw4w5c2m2g5edjrtvwbpzhkw24.eu-west-1.es.amazonaws.com"
          },
          "ELASTIC_INDEX": "island-is",
          "CONTENTFUL_SPACE": "8k0h54kbe6bj",
          "CONTENTFUL_ENVIRONMENT": "master",
          "CONTENTFUL_HOST": {
            "dev": "preview.contentful.com",
            "staging": "cdn.contentful.com",
            "prod": "cdn.contentful.com"
          },
          "CONTENTFUL_ENTRY_FETCH_CHUNK_SIZE": {
            "dev": "40",
            "staging": "40",
            "prod": "40"
          },
          "AIR_DISCOUNT_SCHEME_FRONTEND_HOSTNAME": {
            "dev": "loftbru.dev01.devland.is",
            "staging": "loftbru.staging01.devland.is",
            "prod": "loftbru.island.is"
          },
          "S3_BUCKET": {
            "dev": "dev-es-custom-packages",
            "staging": "staging-es-custom-packages",
            "prod": "prod-es-custom-packages"
          },
          "ELASTIC_DOMAIN": "search",
          "NODE_OPTIONS": "--max-old-space-size=2048"
        },
        "secrets": {
          "CONTENTFUL_ACCESS_TOKEN": "/k8s/search-indexer/CONTENTFUL_ACCESS_TOKEN",
          "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY"
        },
        "features": {},
        "containers": [
          {
            "command": "/usr/local/bin/node",
            "args": [
              "/webapp/migrateAws.js"
            ],
            "name": "migrate-aws",
            "resources": {
              "requests": {
                "cpu": "100m",
                "memory": "512Mi"
              },
              "limits": {
                "cpu": "400m",
                "memory": "2048Mi"
              }
            }
          },
          {
            "command": "/usr/local/bin/node",
            "args": [
              "/webapp/migrateElastic.js"
            ],
            "name": "migrate-elastic",
            "resources": {
              "requests": {
                "cpu": "300m",
                "memory": "3072Mi"
              },
              "limits": {
                "cpu": "700m",
                "memory": "4096Mi"
              }
            }
          },
          {
            "command": "/usr/local/bin/node",
            "args": [
              "/webapp/migrateKibana.js"
            ],
            "name": "migrate-kibana",
            "resources": {
              "requests": {
                "cpu": "100m",
                "memory": "512Mi"
              },
              "limits": {
                "cpu": "400m",
                "memory": "2048Mi"
              }
            }
          }
        ]
      },
      "replicaCount": {
        "min": 1,
        "max": 1,
        "default": 1
      },
      "extraAttributes": {
        "dev": {
          "progressDeadlineSeconds": 1500
        },
        "staging": {
          "progressDeadlineSeconds": 1500
        },
        "prod": {
          "progressDeadlineSeconds": 1500
        }
      }
    }
  }
}