{
  "judicial-system-web": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/readiness",
        "timeoutSeconds": 10,
        "initialDelaySeconds": 3
      },
      "env": {
        "API_URL": {
          "prod": "https://rettarvorslugatt.island.is"
        }
      },
      "features": {},
      "name": "judicial-system-web",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "NATIONAL_REGISTRY_API_KEY": "/k8s/judicial-system/NATIONAL_REGISTRY_API_KEY",
        "LAWYERS_ICELAND_API_KEY": "/k8s/judicial-system/LAWYERS_ICELAND_API_KEY",
        "SUPPORT_EMAIL": "/k8s/judicial-system/SUPPORT_EMAIL"
      },
      "ingress": {
        "primary": {
          "host": {
            "dev": "judicial-system",
            "staging": "judicial-system",
            "prod": "rettarvorslugatt.island.is"
          },
          "paths": [
            "/"
          ],
          "extraAnnotations": {
            "dev": {
              "nginx.ingress.kubernetes.io/proxy-buffering": "on",
              "nginx.ingress.kubernetes.io/proxy-buffer-size": "8k"
            },
            "staging": {
              "nginx.ingress.kubernetes.io/proxy-buffering": "on",
              "nginx.ingress.kubernetes.io/proxy-buffer-size": "8k"
            },
            "prod": {
              "nginx.ingress.kubernetes.io/proxy-buffering": "on",
              "nginx.ingress.kubernetes.io/proxy-buffer-size": "8k"
            }
          }
        }
      },
      "namespace": "judicial-system",
      "serviceAccountEnabled": false,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "200m",
          "memory": "256Mi"
        },
        "requests": {
          "cpu": "15m",
          "memory": "128Mi"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": []
    }
  }
}