version: '3.3'

services:
  redis-cluster:
    container_name: gha_cache_redis_cluster
    image: docker.io/grokzen/redis-cluster:6.0.16
    privileged: true
    environment:
      - IP=0.0.0.0
    ports:
      - '7000-7005:7000-7005'
