apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: api
spec:
  backendType: systemManager
  data:
    {{- range $key, $value := .Values.secrets }}
    - name: {{ $key }}
      key: {{ $value | quote }}
    {{- end }}