version: '3.3'

services:
  localstack:
    image: docker.io/localstack/localstack:0.13.1
    networks:
      - local
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs

networks:
  local:
