version: '3.3'

services:
  localstack:
    image: public.ecr.aws/localstack/localstack
    networks:
      - local
    ports:
      - 4566:4566
    environment:
      - SERVICES=sqs

networks:
  local:
