{
  "services-auth-personal-representative-public": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/health/check",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        }
      },
      "features": {},
      "name": "services-auth-personal-representative-public",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY"
      },
      "ingress": {
        "primary": {
          "host": {
            "dev": "personal-representative-public-xrd.internal.dev01.devland.is",
            "staging": "personal-representative-public-xrd.internal.staging01.devland.is",
            "prod": "personal-representative-public-xrd.internal.innskra.island.is"
          },
          "paths": [
            "/"
          ],
          "public": false
        }
      },
      "namespace": "personal-representative",
      "serviceAccountEnabled": false,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "400m",
          "memory": "512Mi"
        },
        "requests": {
          "cpu": "100m",
          "memory": "256Mi"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "image": "services-auth-personal-representative-public",
      "postgres": {
        "name": "servicesauth",
        "username": "servicesauth",
        "passwordSecret": "/k8s/servicesauth/DB_PASSWORD"
      },
      "replicaCount": {
        "default": 2,
        "min": 2,
        "max": 10
      }
    }
  }
}