version: '3.3'

services:
  sut:
    image: ${SUT}
    networks:
      - local
    depends_on:
      - db_judicial_system
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=db_judicial_system
    entrypoint:
      [
        'scripts/_wait-for.sh',
        'db_judicial_system:5432',
        '-t',
        '5',
        '--',
        'yarn',
        'run',
        'test',
        'judicial-system-api',
      ]

  db_judicial_system:
    ports: []
