{
  "skilavottord-ws": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "IDENTITY_SERVER_ISSUER_URL": {
          "dev": "https://identity-server.dev01.devland.is",
          "staging": "https://identity-server.staging01.devland.is",
          "prod": "https://innskra.island.is"
        }
      },
      "features": {},
      "name": "skilavottord-ws",
      "grantNamespaces": [
        "application-system"
      ],
      "grantNamespacesEnabled": true,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "SAMGONGUSTOFA_SOAP_URL": "/k8s/skilavottord-ws/SAMGONGUSTOFA_SOAP_URL",
        "SAMGONGUSTOFA_REST_AUTH_URL": "/k8s/skilavottord-ws/SAMGONGUSTOFA_REST_AUTH_URL",
        "SAMGONGUSTOFA_REST_DEREG_URL": "/k8s/skilavottord-ws/SAMGONGUSTOFA_REST_DEREG_URL",
        "FJARSYSLA_REST_URL": "/k8s/skilavottord-ws/FJARSYSLA_REST_URL",
        "SAMGONGUSTOFA_REST_PASS": "/k8s/skilavottord/SAMGONGUSTOFA_REST_PASS",
        "SAMGONGUSTOFA_SOAP_PASS": "/k8s/skilavottord/SAMGONGUSTOFA_SOAP_PASS",
        "FJARSYSLA_REST_PASS": "/k8s/skilavottord/FJARSYSLA_REST_PASS",
        "SAMGONGUSTOFA_SOAP_USER": "/k8s/skilavottord/SAMGONGUSTOFA_SOAP_USER",
        "SAMGONGUSTOFA_REST_USER": "/k8s/skilavottord/SAMGONGUSTOFA_REST_USER",
        "FJARSYSLA_REST_USER": "/k8s/skilavottord/FJARSYSLA_REST_USER"
      },
      "ingress": {
        "primary": {
          "host": {
            "dev": [
              "beta"
            ],
            "staging": [
              "beta"
            ],
            "prod": [
              "",
              "www.island.is"
            ]
          },
          "paths": [
            "/app/skilavottord/api/graphql"
          ]
        }
      },
      "namespace": "skilavottord",
      "serviceAccountEnabled": false,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "cpu": "400m",
          "memory": "512Mi"
        },
        "requests": {
          "cpu": "40m",
          "memory": "256Mi"
        }
      },
      "xroadConfig": [],
      "files": [],
      "volumes": [],
      "postgres": {
        "name": "skilavottord",
        "username": "skilavottord",
        "passwordSecret": "/k8s/skilavottord/DB_PASSWORD"
      },
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          }
        ],
        "postgres": {
          "name": "skilavottord",
          "username": "skilavottord",
          "passwordSecret": "/k8s/skilavottord/DB_PASSWORD"
        }
      }
    }
  }
}