# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    tag: latest_master

web:
  env:
    API_URL: 'http://deploy-dev-api/api'

api:
  secrets:
    CONTENTFUL_ACCESS_TOKEN: '/k8s/api/CONTENTFUL_ACCESS_TOKEN'
  env:
    PORT: 3333

gjafakort-api:
  environment:
    yay_url:
    yay_api_key_path: "/k8s/gjafakort/YAY_API_KEY"
    yay_secret_key_path: "/k8s/gjafakort/YAY_SECRET_KEY"
    ferdalag_url:
    application_url: "http://web-gjafakort-application"
    ferdalag_api_key_path: "/k8s/gjafakort/FERDALAG_API_KEY"
    saml_entry_point:
    auth_audience:
    auth_jwt_secret: "/k8s/gjafakort/api/AUTH_JWT_SECRET"
    rsk_url:
    rsk_username: "rf_api_island.is"
    rsk_api_password_path: "/k8s/shared/api/RSK_API_PASSWORD"
    redis_url:
    cache_time_to_live:
    sentry_dsn:

gjafakort-web:
  environment:
    sentry_auth_token: "/k8s/gjafakort/web/SENTRY_AUTH_TOKEN"
    sentry_dsn:
    sentry_org:
    sentry_project:
gjafakort-application:
  postgres:
    host: 'host'
    name: 'name'
    username: 'username'
    password_secret_path: '/k8s/gjafakort/application/DB_PASSWORD'
    sentry_dsn:
