apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gjafakort-web.fullname" . }}
  labels:
    {{- include "gjafakort-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.default }}
  selector:
    matchLabels:
      {{- include "gjafakort-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gjafakort-web.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gjafakort-web.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 50
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 50
            periodSeconds: 10
          env:
            - name: WEB_PUBLIC_URL
              value: "https://{{ (index .Values.ingress.hosts 0).host }}"
            - name: API_URL
              value: "http://web-gjafakort-api/api"
            - name: SENTRY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gjafakort-web
                  key: SENTRY_AUTH_TOKEN
            - name: SENTRY_DSN
              value: {{ .sentry_dsn }}
            - name: SENTRY_ORG
              value: {{ .sentry_org }}
            - name: SENTRY_PROJECT
              value: {{ .sentry_project }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
