apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gjafakort-web
spec:
  backendType: systemManager
  data:
    - name: SENTRY_AUTH_TOKEN
      key: {{ .Values.environment.sentry_auth_token | quote }}
