version: '3.3'
 
services:
  sut:
    build:
      context: .
      dockerfile: ../../../scripts/ci/Dockerfile.test
      args:
        DB_NAME: db_auth_api_backend
        APP: auth_api_ws
    networks:
      - local
    depends_on:
      - db
    environment:
      - TEST_DB_USER=test_db
      - TEST_DB_PASS=test_db
      - TEST_DB_NAME=test_db
      - DB_HOST=db
    volumes:
      - ../../..:/code
      
  db:
    ports: []