auth-admin-api:
  enabled: true
  env:
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://innskra.island.is'
    IDS_ISSUER: 'https://innskra.island.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'driving-license-use-v1-endpoint-for-v2-comms'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'innskra.island.is'
          paths:
            - '/backend'
  namespace: 'identity-server'
  replicaCount:
    default: 3
    max: 10
    min: 3
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-admin-web:
  enabled: true
  env:
    BASE_URL: 'https://innskra.island.is/admin'
    IDENTITYSERVER_DOMAIN: 'innskra.island.is'
    IDENTITYSERVER_ID: 'identity-server'
    NEXTAUTH_URL: 'https://innskra.island.is/admin/api/auth'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'driving-license-use-v1-endpoint-for-v2-comms'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-web'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'innskra.island.is'
          paths:
            - '/admin'
  namespace: 'identity-server'
  replicaCount:
    default: 3
    max: 10
    min: 3
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-public-api:
  enabled: true
  env:
    IDENTITY_SERVER_ISSUER_URL: 'https://innskra.island.is'
    IDS_ISSUER: 'https://innskra.island.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    PUBLIC_URL: 'https://innskra.island.is/api'
    SERVERSIDE_FEATURES_ON: 'driving-license-use-v1-endpoint-for-v2-comms'
    XROAD_BASE_PATH: 'http://securityserver.island.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.island.is/r1/IS'
    XROAD_CLIENT_ID: 'IS/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_API_PATH: '/SKRA-Protected/Einstaklingar-v1'
    XROAD_NATIONAL_REGISTRY_CLIENT_ID: 'IS/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_MEMBER_CODE: '6503760649'
    XROAD_NATIONAL_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379"]'
    XROAD_NATIONAL_REGISTRY_SERVICE_PATH: 'IS/GOV/6503760649/SKRA-Protected/Einstaklingar-v1'
    XROAD_RSK_MEMBER_CODE: '5402696029'
    XROAD_RSK_PROCURING_PATH: 'IS/GOV/5402696029/Skatturinn/prokura-v1'
    XROAD_RSK_PROCURING_REDIS_NODES: '["clustercfg.general-redis-cluster-group.dnugi2.euw1.cache.amazonaws.com:6379"]'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-public-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'innskra.island.is'
          pathType: 'Prefix'
          paths:
            - '/api(/|$)(.*)'
  namespace: 'identity-server'
  replicaCount:
    default: 3
    max: 10
    min: 3
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
global:
  env:
    AUDIT_GROUP_NAME: '/island-is/audit-log'
    AWS_REGION: 'eu-west-1'
    PORT: '3333'
    name: 'prod'
  image:
    tag: 'latest_master'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'
namespaces:
  labels: {}
  namespaces:
    - 'identity-server'
personal-representative:
  enabled: true
  env:
    IDENTITY_SERVER_ISSUER_URL: 'https://innskra.island.is'
    IDS_ISSUER: 'https://innskra.island.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'driving-license-use-v1-endpoint-for-v2-comms'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/personal-representative'
  ingress:
    demoALB-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'island.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-xrd.internal.innskra.island.is'
          paths:
            - '/'
  namespace: 'identity-server'
  replicaCount:
    default: 3
    max: 10
    min: 3
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
personal-representative-public:
  enabled: true
  env:
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://innskra.island.is'
    IDS_ISSUER: 'https://innskra.island.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: 'driving-license-use-v1-endpoint-for-v2-comms'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/personal-representative-public'
  ingress:
    demoALB-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'island.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-xrd.internal.innskra.island.is'
          paths:
            - '/'
  namespace: 'identity-server'
  replicaCount:
    default: 3
    max: 10
    min: 3
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
