auth-admin-api:
  enabled: true
  env:
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          paths:
            - '/backend'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-admin-web:
  enabled: true
  env:
    BASE_URL: 'https://identity-server.staging01.devland.is/admin'
    IDENTITYSERVER_DOMAIN: 'identity-server.staging01.devland.is'
    IDENTITYSERVER_ID: 'identity-server'
    NEXTAUTH_URL: 'https://identity-server.staging01.devland.is/admin/api/auth'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-web'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          paths:
            - '/admin'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-api:
  enabled: true
  env:
    COMPANY_REGISTRY_XROAD_PROVIDER_ID: 'IS-TEST/GOV/5402696029/Skatturinn/ft-v1'
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    PUBLIC_URL: 'https://identity-server.staging01.devland.is/api'
    SERVERSIDE_FEATURES_ON: ''
    XROAD_BASE_PATH: 'http://securityserver.staging01.devland.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.staging01.devland.is/r1/IS-TEST'
    XROAD_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_API_PATH: '/SKRA-Protected/Einstaklingar-v1'
    XROAD_NATIONAL_REGISTRY_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_MEMBER_CODE: '6503760649'
    XROAD_NATIONAL_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
    XROAD_NATIONAL_REGISTRY_SERVICE_PATH: 'IS-TEST/GOV/6503760649/SKRA-Protected/Einstaklingar-v1'
    XROAD_RSK_MEMBER_CODE: '5402696029'
    XROAD_RSK_PROCURING_PATH: 'IS-TEST/GOV/5402696029/Skatturinn/prokura-v1'
    XROAD_RSK_PROCURING_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
    XROAD_TLS_BASE_PATH: 'https://securityserver.staging01.devland.is'
    XROAD_TLS_BASE_PATH_WITH_ENV: 'https://securityserver.staging01.devland.is/r1/IS-TEST'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          pathType: 'Prefix'
          paths:
            - '/api(/|$)(.*)'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-public-api:
  enabled: true
  env:
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    PUBLIC_URL: 'https://identity-server.staging01.devland.is/api'
    SERVERSIDE_FEATURES_ON: ''
    XROAD_BASE_PATH: 'http://securityserver.staging01.devland.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.staging01.devland.is/r1/IS-TEST'
    XROAD_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_API_PATH: '/SKRA-Protected/Einstaklingar-v1'
    XROAD_NATIONAL_REGISTRY_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_MEMBER_CODE: '6503760649'
    XROAD_NATIONAL_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
    XROAD_NATIONAL_REGISTRY_SERVICE_PATH: 'IS-TEST/GOV/6503760649/SKRA-Protected/Einstaklingar-v1'
    XROAD_RSK_MEMBER_CODE: '5402696029'
    XROAD_RSK_PROCURING_PATH: 'IS-TEST/GOV/5402696029/Skatturinn/prokura-v1'
    XROAD_RSK_PROCURING_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
    XROAD_TLS_BASE_PATH: 'https://securityserver.staging01.devland.is'
    XROAD_TLS_BASE_PATH_WITH_ENV: 'https://securityserver.staging01.devland.is/r1/IS-TEST'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-public-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          pathType: 'Prefix'
          paths:
            - '/api(/|$)(.*)'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
global:
  env:
    AUDIT_GROUP_NAME: '/island-is/audit-log'
    AWS_REGION: 'eu-west-1'
    PORT: '3333'
    name: 'staging'
  image:
    tag: 'latest_master'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'
identity-server:
  enabled: true
  env:
    AWS__SystemsManager__ParameterStore__DataProtectionPrefix: '/k8s/identity-server/DataProtectionSecret'
    Application__MinCompletionPortThreads: ''
    CacheSettings__Enabled: 'true'
    CacheSettings__Memcached__Address: 'identity-server.ab9ckb.cfg.euw1.cache.amazonaws.com'
    CacheSettings__Memcached__Port: '11211'
    CacheSettings__Redis__Address: 'clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com'
    CacheSettings__Redis__Port: '6379'
    IdentityServer__EnableDelegation: ''
    IdentityServer__EnableFakeLogin: 'true'
    IdentityServer__EnableFeatureDeploymentWildcards: 'true'
    NODE_OPTIONS: '--max-old-space-size=208'
    PersistenceSettings__BaseAddress: 'http://web-services-auth-api'
    PersistenceSettings__UserProfileBaseAddress: 'http://web-service-portal-api.service-portal.svc.cluster.local'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/identity-server'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          paths:
            - '/'
  namespace: 'identity-server'
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    AudkenniSettings__ClientId: '/k8s/identity-server/AudkenniClientId'
    AudkenniSettings__ClientSecret: '/k8s/identity-server/AudkenniClientSecret'
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    FeatureFlags__ConfigCatSdkKey: '/k8s/configcat/CONFIGCAT_SDK_KEY'
    IdentityServer__FakePersons: '/k8s/identity-server/FakePersons'
    IdentityServer__SigningCertificate__Passphrase: '/k8s/identity-server/SigningCertificatePassphrase'
    PersistenceSettings__AccessTokenManagementSettings__ClientSecret: '/k8s/identity-server/ClientSecret'
    Scopes__Admin__RootAccessList: '/k8s/identity-server/AdminRootAccessList'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: 'arn:aws:iam::261174024191:role/identity-server'
    create: true
    name: 'identity-server'
namespaces:
  labels: {}
  namespaces:
    - 'identity-server'
personal-representative:
  enabled: true
  env:
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/personal-representative'
  ingress:
    demoALB-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'staging01.devland.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-xrd.internal.staging01.devland.is'
          paths:
            - '/'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
personal-representative-public:
  enabled: true
  env:
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  hpa:
    scaling:
      metric:
        cpuAverageUtilization: 70
        nginxRequestsIrate: 2
      replicas:
        max: 3
        min: 2
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/personal-representative-public'
  ingress:
    demoALB-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'staging01.devland.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-xrd.internal.staging01.devland.is'
          paths:
            - '/'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
