auth-admin-api:
  enabled: true
  env:
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          paths:
            - '/backend'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-admin-web:
  enabled: true
  env:
    BASE_URL: 'https://identity-server.staging01.devland.is/admin'
    IDENTITYSERVER_DOMAIN: 'identity-server.staging01.devland.is'
    IDENTITYSERVER_ID: 'identity-server'
    NEXTAUTH_URL: 'https://identity-server.staging01.devland.is/admin/api/auth'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-admin-web'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          paths:
            - '/admin'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-api:
  enabled: true
  env:
    COMPANY_REGISTRY_XROAD_PROVIDER_ID: 'IS-TEST/GOV/5402696029/Skatturinn/ft-v1'
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    PUBLIC_URL: 'https://identity-server.staging01.devland.is/api'
    SERVERSIDE_FEATURES_ON: ''
    XROAD_BASE_PATH: 'http://securityserver.staging01.devland.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.staging01.devland.is/r1/IS-TEST'
    XROAD_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_API_PATH: '/SKRA-Protected/Einstaklingar-v1'
    XROAD_NATIONAL_REGISTRY_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_MEMBER_CODE: '6503760649'
    XROAD_NATIONAL_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
    XROAD_NATIONAL_REGISTRY_SERVICE_PATH: 'IS-TEST/GOV/6503760649/SKRA-Protected/Einstaklingar-v1'
    XROAD_RSK_MEMBER_CODE: '5402696029'
    XROAD_RSK_PROCURING_PATH: 'IS-TEST/GOV/5402696029/Skatturinn/prokura-v1'
    XROAD_RSK_PROCURING_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          pathType: 'Prefix'
          paths:
            - '/api(/|$)(.*)'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
auth-public-api:
  enabled: true
  env:
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    PUBLIC_URL: 'https://identity-server.staging01.devland.is/api'
    SERVERSIDE_FEATURES_ON: ''
    XROAD_BASE_PATH: 'http://securityserver.staging01.devland.is'
    XROAD_BASE_PATH_WITH_ENV: 'http://securityserver.staging01.devland.is/r1/IS-TEST'
    XROAD_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_API_PATH: '/SKRA-Protected/Einstaklingar-v1'
    XROAD_NATIONAL_REGISTRY_CLIENT_ID: 'IS-TEST/GOV/5501692829/island-is-client'
    XROAD_NATIONAL_REGISTRY_MEMBER_CODE: '6503760649'
    XROAD_NATIONAL_REGISTRY_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
    XROAD_NATIONAL_REGISTRY_SERVICE_PATH: 'IS-TEST/GOV/6503760649/SKRA-Protected/Einstaklingar-v1'
    XROAD_RSK_MEMBER_CODE: '5402696029'
    XROAD_RSK_PROCURING_PATH: 'IS-TEST/GOV/5402696029/Skatturinn/prokura-v1'
    XROAD_RSK_PROCURING_REDIS_NODES: '["clustercfg.general-redis-cluster-group.ab9ckb.euw1.cache.amazonaws.com:6379"]'
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/auth-public-api'
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'identity-server.staging01.devland.is'
          pathType: 'Prefix'
          paths:
            - '/api(/|$)(.*)'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
global:
  env:
    AUDIT_GROUP_NAME: '/island-is/audit-log'
    AWS_REGION: 'eu-west-1'
    PORT: '3333'
    name: 'staging'
  image:
    tag: 'latest_master'
  initContainer:
    env:
      AWS_REGION: 'eu-west-1'
namespaces:
  labels: {}
  namespaces:
    - 'identity-server'
personal-representative:
  enabled: true
  env:
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/personal-representative'
  ingress:
    demoALB-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'staging01.devland.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-xrd.internal.staging01.devland.is'
          paths:
            - '/'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
personal-representative-public:
  enabled: true
  env:
    DB_REPLICAS_HOST: ''
    IDENTITY_SERVER_ISSUER_URL: 'https://identity-server.staging01.devland.is'
    IDS_ISSUER: 'https://identity-server.staging01.devland.is'
    NODE_OPTIONS: '--max-old-space-size=208'
    SERVERSIDE_FEATURES_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: '/liveness'
      timeoutSeconds: 3
  image:
    repository: '821090935708.dkr.ecr.eu-west-1.amazonaws.com/personal-representative-public'
  ingress:
    demoALB-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-external-alb'
      hosts:
        - host: 'staging01.devland.is'
          paths:
            - '/'
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: 'nginx-internal-alb'
      hosts:
        - host: 'personal-representative-xrd.internal.staging01.devland.is'
          paths:
            - '/'
  namespace: 'identity-server'
  replicaCount:
    default: 2
    max: 3
    min: 2
  resources:
    limits:
      cpu: '200m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
  secrets:
    CONFIGCAT_SDK_KEY: '/k8s/configcat/CONFIGCAT_SDK_KEY'
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
