{
  "xroad-collector": {
    "serviceDef": {
      "liveness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "NODE_TLS_REJECT_UNAUTHORIZED": "0",
        "ELASTIC_NODE": {
          "dev": "https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com",
          "staging": "https://vpc-search-q6hdtjcdlhkffyxvrnmzfwphuq.eu-west-1.es.amazonaws.com",
          "prod": "https://vpc-search-mw4w5c2m2g5edjrtvwbpzhkw24.eu-west-1.es.amazonaws.com"
        }
      },
      "features": {},
      "name": "xroad-collector",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY"
      },
      "ingress": {},
      "namespace": "xroad-collector",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "limits": {
          "memory": "256Mi",
          "cpu": "200m"
        },
        "requests": {
          "memory": "128Mi",
          "cpu": "100m"
        }
      },
      "xroadConfig": [
        {
          "config": {
            "env": {
              "XROAD_BASE_PATH": {
                "prod": "http://securityserver.island.is"
              },
              "XROAD_BASE_PATH_WITH_ENV": {
                "staging": "http://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "http://securityserver.island.is/r1/IS"
              },
              "XROAD_TLS_BASE_PATH": {
                "dev": "https://securityserver.dev01.devland.is",
                "staging": "https://securityserver.staging01.devland.is",
                "prod": "https://securityserver.island.is"
              },
              "XROAD_TLS_BASE_PATH_WITH_ENV": {
                "dev": "https://securityserver.dev01.devland.is/r1/IS-DEV",
                "staging": "https://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "https://securityserver.island.is/r1/IS"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_CLIENT_ID": {
                "dev": "IS-DEV/GOV/10000/island-is-client",
                "staging": "IS-TEST/GOV/5501692829/island-is-client",
                "prod": "IS/GOV/5501692829/island-is-client"
              }
            }
          }
        }
      ],
      "files": [],
      "volumes": [],
      "image": "services-xroad-collector",
      "accountName": "xroad-collector",
      "cmds": "node",
      "args": [
        "--no-experimental-fetch",
        "main.js"
      ],
      "extraAttributes": {
        "dev": {
          "schedule": "0 2 * * *"
        },
        "staging": {
          "schedule": "0 2 * * *"
        },
        "prod": {
          "schedule": "0 2 * * *"
        }
      }
    }
  }
}