version: '3.3'

services:
  redis_cluster:
    container_name: api_redis_cluster
    image: docker.io/grokzen/redis-cluster:6.0.16
    networks:
      - local
    privileged: true
    environment:
      - IP=0.0.0.0
    ports:
      - '7000-7005:7000-7005'

networks:
  local:
