name: Monorepo pipeline

on:
  push:
    branches:
      - 'master'
      - 'release/**'
      - 'hotfix/**'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

env:
  DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/

jobs:
  prepare:
    runs-on: ubuntu-20.04
    timeout-minutes: 40 #pulling dependencies potentially twice - host OS and docker layer

    env:
      AFFECTED_ALL: ${{ secrets.AFFECTED_ALL }}
      CHUNK_SIZE: '2'

    outputs:
      GIT_BRANCH: ${{ steps.git_refs.outputs.GIT_BRANCH }}
      DOCKER_TAG: ${{ steps.docker_tags.outputs.DOCKER_TAG }}
      LAST_GOOD_BUILD_DOCKER_TAG: ${{ steps.git_nx_base.outputs.LAST_GOOD_BUILD_DOCKER_TAG }}
      PUBLISH: ${{ steps.publish_flag.outputs.PUBLISH }}
      TEST_CHUNKS: ${{ steps.test_projects.outputs.CHUNKS }}
      LINT_CHUNKS: ${{ steps.lint_projects.outputs.CHUNKS }}
      UNAFFECTED: ${{ steps.unaffected.outputs.UNAFFECTED }}
      BUILD_CHUNKS: ${{ steps.build_projects.outputs.CHUNKS }}
      BUILD_MAP: ${{ steps.build_map.outputs.BUILD_MAP }}
      node-modules-hash: ${{ steps.calculate_node_modules_hash.outputs.node-modules-hash }}
      generated-files-cache-key: ${{ steps.calculate_generated_files_cache_key.outputs.generated-files-cache-key }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git refs
        id: git_refs
        run: |
          export GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF/refs\/heads\//}}"
          if [[ ! -z "$GITHUB_BASE_REF" ]]
          then
           # a PR
           GIT_BASE_BRANCH=$GITHUB_BASE_REF
          else
           # on master
           GIT_BASE_BRANCH=master
          fi
          echo "::set-env name=GIT_BRANCH::${GIT_BRANCH}"
          echo "::set-output name=GIT_BRANCH::${GIT_BRANCH}"
          echo "::set-env name=GIT_BASE_BRANCH::${GIT_BASE_BRANCH}"
          echo "Base branch is '${GIT_BASE_BRANCH}'"
          echo "Branch is '${GIT_BRANCH}'"

      - name: Generate docker image tag
        id: docker_tags
        run: |
          export DOCKER_BRANCH_TAG=$(echo ${GIT_BRANCH} | tr "/." "-" )
          export DOCKER_TAG=${GITHUB_RUN_NUMBER}_${DOCKER_BRANCH_TAG}_${GITHUB_SHA:0:7}
          echo "Docker tag will be ${DOCKER_TAG}"
          echo "::set-output name=DOCKER_TAG::${DOCKER_TAG}"
          echo "::set-env name=DOCKER_TAG::${DOCKER_TAG}"

      - run: |
          echo "::set-env name=HEAD::${GITHUB_SHA}"
        id: git_nx_head
        name: Preparing HEAD tag

      - run: |
          source ./scripts/00_prepare-base-tags.sh
          echo "::set-env name=BASE::${BASE}"
          echo "::set-output name=LAST_GOOD_BUILD_DOCKER_TAG::${LAST_GOOD_BUILD_DOCKER_TAG}"
        id: git_nx_base
        name: Preparing BASE tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set publish flag
        id: publish_flag
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export PUBLISH=false
          else
            export PUBLISH=true
          fi
          echo "::set-output name=PUBLISH::${PUBLISH}"

      - name: Calculate cache key for node_modules
        id: calculate_node_modules_hash
        run: |
          PACKAGE_JSON_HASH=$(cat package.json | jq '{resolutions,dependencies,devDependencies}' | sha1sum -t | cut -f1 -d" ")
          echo "PACKAGE_JSON_HASH: $PACKAGE_JSON_HASH"
          export NODE_MODULES_HASH=${{ runner.os }}-${{ hashFiles('yarn.lock') }}-$PACKAGE_JSON_HASH
          echo "NODE_MODULES_HASH: $NODE_MODULES_HASH"
          echo "::set-output name=node-modules-hash::$NODE_MODULES_HASH"

      - name: Calculate cache keys for generated files
        id: calculate_generated_files_cache_key
        run: |
          export HASH=${{ hashFiles('libs/api/domains/cms/src/lib/generated/contentfulTypes.d.ts', 'apps/**/codegen.yml', 'apps/**/modules/**.ts?', 'libs/**/modules/**.ts?', 'apps/**/models/**.ts?', 'libs/**/models/**.ts?', 'apps/**/dto/**.ts?', 'libs/**/dto/**.ts?', 'apps/**/enums/**.ts?', 'libs/**/enums/**.ts?', 'apps/**/queries/**.ts?', 'libs/**/queries/**.ts?', 'apps/**/*.model.ts', 'libs/**/*.model.ts', 'apps/**/*.resolver.ts', 'libs/**/*.resolver.ts', 'apps/**/*.service.ts', 'libs/**/*.service.ts', 'apps/air-discount-scheme/web/screens/**/*.tsx', 'apps/air-discount-scheme/web/i18n/withLocale.tsx', 'apps/air-discount-scheme/web/components/AppLayout/AppLayout.tsx', 'apps/air-discount-scheme/web/components/Header/Header.tsx', 'apps/gjafakort/api/src/**/typeDefs.ts') }}
          export GENERATED_FILES_KEY=${{ runner.os }}-$HASH-generated-files
          echo "GENERATED_FILES_KEY: $GENERATED_FILES_KEY"
          echo "::set-output name=generated-files-cache-key::$GENERATED_FILES_KEY"

      - name: Cache for NodeJS dependencies - Docker layer
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ steps.calculate_node_modules_hash.outputs.node-modules-hash }}-docker-deps

      - name: Cache for NodeJS dependencies - Docker layer
        uses: actions/cache@v2
        with:
          path: cache_output
          key: ${{ steps.calculate_node_modules_hash.outputs.node-modules-hash }}-docker-output-base

      - name: Cache for NodeJS dependencies - host OS
        id: node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ steps.calculate_node_modules_hash.outputs.node-modules-hash }}-yarn

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: latest

      - name: Building NodeJS dependencies
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: ./scripts/10_prepare-deps.sh

      - name: set BRANCH env var
        run: echo "::set-env name=BRANCH::${GIT_BRANCH}"

      - name: Cache for generated files
        id: generated-files-cache
        uses: actions/cache@v2
        with:
          path: generated_files.tar.gz
          key: ${{ steps.calculate_generated_files_cache_key.outputs.generated-files-cache-key }}

      - name: Generate schemas
        if: steps.generated-files-cache.outputs.cache-hit != 'true'
        run: tar zcvf generated_files.tar.gz $(./scripts/get-files-touched-by.sh yarn schemas --all | xargs realpath --relative-to $(pwd))

      - name: Security audit Node modules
        run: ./scripts/20_security-audit.sh

      - name: License audit Node modules
        run: ./scripts/20_license-audit.sh

      - name: Prepare lint targets
        id: lint_projects
        run: |
          CHUNKS=$(CHUNK_SIZE=7 ./scripts/generate-chunks.sh lint)
          echo "::set-output name=CHUNKS::{\"projects\":$CHUNKS}"

      - name: Prepare test targets
        id: test_projects
        run: |
          CHUNKS=$(CHUNK_SIZE=7 ./scripts/generate-chunks.sh test)
          echo "::set-output name=CHUNKS::{\"projects\":$CHUNKS}"

      - name: Prepare native build targets
        id: build_projects
        run: |
          CHUNKS=$(CHUNK_SIZE=7 ./scripts/generate-chunks.sh build)
          echo "::set-output name=CHUNKS::{\"projects\":$CHUNKS}"

      - name: Prepare docker build targets
        id: build_map
        run: |
          MAP=$(./scripts/generate-build-map.sh docker-express docker-next docker-static)
          echo "MAP: '$MAP'"
          echo "::set-output name=BUILD_MAP::$MAP"

      - name: Gather unaffected docker images
        id: unaffected
        run: |
          UNAFFECTED=$(./scripts/list-unaffected.sh docker-next docker-express docker-static)
          echo "::set-output name=UNAFFECTED::$UNAFFECTED"

  tests:
    needs:
      - prepare
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      AFFECTED_PROJECTS: ${{ matrix.projects }}
      GIT_BRANCH: ${{ needs.prepare.outputs.GIT_BRANCH}}
      DOCKER_TAG: ${{ needs.prepare.outputs.DOCKER_TAG}}
      MAX_JOBS: 4
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.TEST_CHUNKS) }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ matrix.projects != 'dummy' }}

      - name: Cache for dependencies Docker layer
        if: ${{ matrix.projects != 'dummy' }}
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ needs.prepare.outputs.node-modules-hash }}-docker-deps
      - name: Cache for NodeJS dependencies - host OS
        if: ${{ matrix.projects != 'dummy' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ needs.prepare.outputs.node-modules-hash }}-yarn

      - name: Cache for generated files
        if: ${{ matrix.projects != 'dummy' }}
        uses: actions/cache@v2
        with:
          path: generated_files.tar.gz
          key: ${{ needs.prepare.outputs.generated-files-cache-key }}

      - name: Untar generated files
        if: ${{ matrix.projects != 'dummy' }}
        run: tar zxvf generated_files.tar.gz

      - name: Set up Docker Buildx
        if: ${{ matrix.projects != 'dummy' }}
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: latest

      - name: Running tests
        if: ${{ matrix.projects != 'dummy' }}
        run: ./scripts/run-in-parallel.sh 30_test
      # - name: Running E2E tests
      #   run: yarn run affected:e2e --base origin/master

  formatting:
    needs:
      - prepare
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Cache for NodeJS dependencies - host OS
        id: node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ needs.prepare.outputs.node-modules-hash }}-yarn
      - name: Check formatting
        run: ./scripts/20_check-formatting.sh

  linting:
    needs:
      - prepare
    runs-on: ubuntu-20.04
    timeout-minutes: 25 # linting has proven to be quite resource intensive
    env:
      AFFECTED_PROJECTS: ${{ matrix.projects }}
      MAX_JOBS: 4
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.LINT_CHUNKS) }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ matrix.projects != 'dummy' }}

      - name: Cache for NodeJS dependencies - host OS
        if: ${{ matrix.projects != 'dummy' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ needs.prepare.outputs.node-modules-hash }}-yarn

      - name: Cache for generated files
        if: ${{ matrix.projects != 'dummy' }}
        uses: actions/cache@v2
        with:
          path: generated_files.tar.gz
          key: ${{ needs.prepare.outputs.generated-files-cache-key }}

      - name: Untar generated files
        if: ${{ matrix.projects != 'dummy' }}
        run: tar zxvf generated_files.tar.gz

      - name: Linting
        if: ${{ matrix.projects != 'dummy' }}
        run: ./scripts/run-in-parallel-native.sh lint

  native-build:
    if: needs.prepare.outputs.PUBLISH != 'true'
    needs:
      - prepare
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    env:
      AFFECTED_PROJECTS: ${{ matrix.projects }}
      MAX_JOBS: 4
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.BUILD_CHUNKS) }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ matrix.projects != 'dummy' }}

      - name: Cache for NodeJS dependencies - host OS
        if: ${{ matrix.projects != 'dummy' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ needs.prepare.outputs.node-modules-hash }}-yarn

      - name: Cache for generated files
        if: ${{ matrix.projects != 'dummy' }}
        uses: actions/cache@v2
        with:
          path: generated_files.tar.gz
          key: ${{ needs.prepare.outputs.generated-files-cache-key }}

      - name: Untar generated files
        if: ${{ matrix.projects != 'dummy' }}
        run: tar zxvf generated_files.tar.gz

      - name: Building
        if: ${{ matrix.projects != 'dummy' }}
        run: ./scripts/run-in-parallel-native.sh build

  docker-build:
    if: needs.prepare.outputs.PUBLISH == 'true'
    needs:
      - prepare
      - tests
    runs-on: ubuntu-20.04
    timeout-minutes: 25
    env:
      AFFECTED_ALL: ${{ secrets.AFFECTED_ALL }}
      GIT_BRANCH: ${{ needs.prepare.outputs.GIT_BRANCH}}
      DOCKER_TAG: ${{ needs.prepare.outputs.DOCKER_TAG}}
      MAX_JOBS: 4
      PUBLISH: true
    strategy:
      fail-fast: false
      matrix:
        docker-type:
          - express
          - next
          - static
    steps:
      - name: Gather apps
        id: gather
        run: |
          AFFECTED_PROJECTS=$(echo '${{ needs.prepare.outputs.BUILD_MAP }}' | jq -r '.["docker-${{ matrix.docker-type }}"]')
          if [[ "$AFFECTED_PROJECTS" == "null" ]]; then
            # Early exit
            exit 1
          fi
          echo "::set-env name=AFFECTED_PROJECTS::$AFFECTED_PROJECTS"
        continue-on-error: true
      - uses: actions/checkout@v2
        if: steps.gather.conclusion == 'success'
      - name: Cache for generated files
        if: steps.gather.conclusion == 'success'
        uses: actions/cache@v2
        with:
          path: generated_files.tar.gz
          key: ${{ needs.prepare.outputs.generated-files-cache-key }}

      - name: Untar generated files
        if: steps.gather.conclusion == 'success'
        run: tar zxvf generated_files.tar.gz

      - name: Cache for dependencies Docker layer
        if: steps.gather.conclusion == 'success'
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: cache_output
          key: ${{ needs.prepare.outputs.node-modules-hash }}-docker-output-base

      - name: Cache for NodeJS dependencies - Docker layer
        if: steps.gather.conclusion == 'success'
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ needs.prepare.outputs.node-modules-hash }}-docker-deps

      - name: Docker login to ECR repo
        if: steps.gather.conclusion == 'success'
        run: ./scripts/docker-login-ecr.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Docker Buildx
        if: steps.gather.conclusion == 'success'
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: latest

      - name: Building Docker images
        if: steps.gather.conclusion == 'success'
        run: ./scripts/run-in-parallel.sh 90_docker-${{ matrix.docker-type }}

  retag-unaffected:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    needs:
      - docker-build
      - prepare
    if: needs.prepare.outputs.PUBLISH == 'true'
    env:
      GIT_BRANCH: ${{ needs.prepare.outputs.GIT_BRANCH}}
      DOCKER_TAG: ${{ needs.prepare.outputs.DOCKER_TAG}}
      LAST_GOOD_BUILD_DOCKER_TAG: ${{ needs.prepare.outputs.LAST_GOOD_BUILD_DOCKER_TAG}}
      UNAFFECTED: ${{ needs.prepare.outputs.UNAFFECTED}}

    steps:
      - uses: actions/checkout@v2
      - name: Retag unaffected Docker images
        run: ./scripts/retag-unaffected.sh "$UNAFFECTED"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    runs-on: ubuntu-20.04
    if: needs.prepare.outputs.PUBLISH == 'true'
    needs:
      - retag-unaffected
      - prepare
    env:
      GIT_BRANCH: ${{ needs.prepare.outputs.GIT_BRANCH}}
      DOCKER_TAG: ${{ needs.prepare.outputs.DOCKER_TAG}}
    strategy:
      matrix:
        service:
          - islandis
          - gjafakort
          - air-discount-scheme
    outputs:
      DEPLOY_FINISHED: ${{ steps.finished.outputs.DEPLOY_FINISHED }}
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Deployment for service
        env:
          SPINNAKER_URL: https://spinnaker-gate.shared.devland.is
          SPINNAKER_WEBHOOK_TOKEN: ${{ secrets.SPINNAKER_WEBHOOK_TOKEN }}
        run: |
          curl -v $SPINNAKER_URL/webhooks/webhook/${{matrix.service}} -H "content-type: application/json" --data-binary @- <<BODY
          {
          "token": "$SPINNAKER_WEBHOOK_TOKEN",
          "branch": "$GIT_BRANCH",
          "parameters": { "docker_tag": "$DOCKER_TAG" }
          }
          BODY

  success:
    runs-on: ubuntu-20.04
    if: always()
    needs:
      - prepare
      - deploy
      - tests
      - linting
      - formatting
      - native-build
    steps:
      # This is easier to clean up when we break up build.yml
      - name: Check deploy success
        if: needs.prepare.outputs.PUBLISH == 'true'
        run: '[[ ${{ needs.deploy.result }} == "success" ]] || exit 1'
      - name: Check tests success
        if: needs.prepare.outputs.PUBLISH != 'true'
        run: '[[ ${{ needs.tests.result }} == "success" ]] || exit 1'
      - name: Check linting success
        if: needs.prepare.outputs.PUBLISH != 'true'
        run: '[[ ${{ needs.linting.result }} == "success" ]] || exit 1'
      - name: Check formatting success
        if: needs.prepare.outputs.PUBLISH != 'true'
        run: '[[ ${{ needs.formatting.result }} == "success" ]] || exit 1'
      - name: Check native-build success
        if: needs.prepare.outputs.PUBLISH != 'true'
        run: '[[ ${{ needs.native-build.result }} == "success" ]] || exit 1'
      - name: Announce success
        run: echo "Build is successful"

  failure-notification:
    runs-on: ubuntu-20.04
    if: failure()
    needs:
      - docker-build
      - prepare
      - linting
      - formatting
      - deploy
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          icon_emoji: ':broken_heart:'
          fields: repo,message,commit,author,action,eventName,ref,workflow,took # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: needs.prepare.outputs.PUBLISH == 'true'
