name: Lint codeowners

on:
  - push
  - workflow_dispatch

jobs:
  codeowners-check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mszostok/codeowners-validator@v0.4.0
        with:
          checks: 'files,owners,duppatterns'
          experimental_checks: 'notowned'
          github_access_token: '${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}'
