name: Lint codeowners

on:
  - push
  - workflow_dispatch

jobs:
  codeowners-check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check indentation
        run: |
          no_different_indentations=$(cat .github/CODEOWNERS | grep -v '^#' | awk NF | sed s/@.*//g | awk '{ print length }' | sort | uniq | wc -l)
          if [[ "$no_different_indentations" != "1" ]]; then
            echo "CODEOWNERS has $no_different_indentations different indentations."
            echo "Make sure that all teams start in the same column."
            cat .github/CODEOWNERS | grep -v '^#' | awk NF
            exit 1
          fi
      - uses: mszostok/codeowners-validator@v0.4.0
        with:
          checks: 'files,owners,duppatterns'
          experimental_checks: 'notowned'
          github_access_token: '${{ secrets.OWNERS_VALIDATOR_GITHUB_SECRET }}'
