on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed
  pull_request:
    types:
      - opened
      - closed
      - synchronize
      - labeled
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: read
  pull-requests: read

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: int128/datadog-actions-metrics@v1
        with:
          # Very expensive custom metrics
          collect-job-metrics: false
          collect-step-metrics: false
          datadog-api-key: ${{ secrets.DD_API_KEY }}
          datadog-site: datadoghq.eu
          send-pull-request-labels: false
