name: Monorepo pipeline - build and deploy

on:
  push:
    branches:
      - fix/runner-debug

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: arc-docker
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: debug
        run: |
          echo "hallo"
