name: Monorepo pipeline - build and deploy

on:
  push:
    branches:
      - chore/runner-debug

defaults:
  run:
    shell: bash

jobs:
  prepare:
    runs-on: arc-runners
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: debug
        run: |
          echo "hallo"

      - name: Lint head
        id: lint-head
        run: |
          AFFECTED_PROJECTS='judicial-system-web, judicial-system-types, judicial-system-digital-mailbox-api, judicial-system-message-handler, judicial-system-formatters, judicial-system-backend, judicial-system-xrd-api, judicial-system-api, judicial-system-scheduler, judicial-system-message, judicial-system-consts, judicial-system-auth'
          lints=$(mktemp -t lint-head.XXXXXX)
          echo "lints-file=$lints" | tee -a "$GITHUB_OUTPUT"
          yarn nx run-many -t lint --projects "$AFFECTED_PROJECTS" |
            tee -a "$lints" | # Show output when running, but preserve pipe-chaining
            grep -oP '(?<=✖ )(\d+)(?= problems)' | # Find number of problems
            awk '{ SUM += $1} END { SUM /= 2; printf "lint-count=%d",SUM }' | # sum number of problems, divide by 2 because each problem summary occurs twice
            tee -a "$GITHUB_OUTPUT" # Finally create output
