name: Upload manifest to argocd repo

on: 
    push: {}

concurrency:
  group: upload-manifest-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
    upload:
      runs-on: arc-runners
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Setup yarn
          uses: ./.github/actions/setup-yarn
        - name: Get manifest data
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: node scripts/ci/docker/get-data.mjs
        
