name: Check dirty files

on:
  pull_request:
    paths:
      - '**'
concurrency:
  group: dirty-fix-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  DIRTY_TOKEN: {{ secret.DIRTY_FIX_BOT_TOKEN }}
  GITHUB_ACTIONS_CACHE_URL: https://cache.dev01.devland.is/
  jobs:
    format:
      runs-on: ubuntu-latest
    - uses: actions/setup-node@v3
          with:
            cache: 'yarn'
            cache-dependency-path: 'yarn.lock'
            node-version: '18'
          - run: yarn install
  - name: NX format:write
          if: ${{ github.event_name == 'pull_request' }}
          run: |
            ./scripts/ci/20_check-formatting.sh "write"
            ./infra/scripts/ci/git-check-dirty.sh "/" "nx format:write" "$DIRTY_TOKEN"