name: Check dirty files

on:
  pull_request:
    paths:
      - '**'
concurrency:
  group: dirty-fix-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash


jobs:
  format:
    runs-on: ubuntu-latest
    env:
      DIRTY_TOKEN: ${{ secrets.DIRTY_FIX_BOT_TOKEN }}
    strategy:
        fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - uses: actions/setup-node@v3
        with:
              cache: 'yarn'
              cache-dependency-path: 'yarn.lock'
              node-version: '18'
      - name: current branch
        run: echo "${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
      - name: install packages
        run: yarn install
      - name: NX format:write
        run: |
            ./scripts/ci/20_check-formatting.sh "write"
            ./infra/scripts/ci/git-check-dirty.sh "/" "nx format:write" "dirty bot"