name: Check dirty files

on:
  pull_request:
    paths:
      - '**'
concurrency:
  group: dirty-fix-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.DIRTY_FIX_BOT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Yarn install
        run: yarn install --immutable
      - name: NX format:write
        if: github.event_name == 'pull_request' && github.actor != 'andes-it'
        run: |
          ./scripts/ci/20_check-formatting.sh "write"
          ./infra/scripts/ci/git-check-dirty.sh "/" "nx format:write" "dirty bot"
