name: Docker Build

on:
  workflow_dispatch:
    inputs:
      projects:
        description: 'Comma-separated list of project names to build.'
        required: true
      runners:
        description: 'The runners to run the jobs on.'
        required: false
        default: 'arc-runners'

concurrency:
  group: container-build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euo pipefail {0}

env:
  # Regsitry to for build images and cache
  IMAGE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY || 'localhost' }}

jobs:
  prepare:
    name: Prepare
    runs-on: ${{ inputs.runners }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      node-image-tag: ${{ steps.build-args.outputs.node-image-tag }}
      playwright-image-tag: ${{ steps.build-args.outputs.playwright-image-tag }}
      container-registry: ${{ steps.build-args.outputs.container-registry }}
    steps:
      - uses: actions/checkout@v4

      - name: Build arg prep
        id: build-args
        run: |
          echo node-image-tag="$(./scripts/ci/get-node-version.mjs)" >>"$GITHUB_OUTPUT"
          yarn info --json @playwright/test | jq -r '.children.Version | "playwright-image-tag=v\(.)-focal"' >>"$GITHUB_OUTPUT"

      - name: Create matrix from input
        id: set-matrix
        env:
          localrun: ${{ !!github.event.localrun }}
        run: |
          # Create a list of objects of the form:
          # [
          #   {
          #     "name": "services-my-service",
          #     "docker": "next|nest|mytype"
          #   },
          #   ...
          # ]
          echo "matrix=$(git ls-files '**/project.json' |
            xargs cat | \
            jq -s -c '{ include: [
              .[]
              | {
                  project: .name,
                  docker: (.targets | keys | map(select(startswith("docker-") and . != "docker-native")) | map(sub("^docker-"; "")) | .[])
                }
              ]
            }')" >>"$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.project }}
    runs-on: ${{ inputs.runners }}
    needs: prepare
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    permissions:
      id-token: write # This is required for requesting the JWT for AWS/ECR login
      contents: read # This is required for actions/checkout

    steps:
      - name: Prepare and debug inputs
        id: inputs
        env:
          # We don't use a repository prefix (e.g. <registry>/island.is/<project>), just the raw project
          image_repository: ${{ env.IMAGE_REPOSITORY }}/${{ matrix.project }}
          localrun: ${{ github.event.localrun }}
        run: |
          echo "Labels: ${{ toJSON(github.event.pull_request.labels) }}"
          echo "Matrix: ${{ toJSON(matrix) }}"
          echo image-repository="$image_repository" >>"$GITHUB_OUTPUT"
          if [[ "$localrun" == true ]]; then
            echo build-cache="type=local,src=/tmp,dest=/tmp,mode=max" >>"$GITHUB_OUTPUT"
          else
            build_cache="type=registry,image-manifest=true,oci-mediatypes=true,ref=$image_repository:cache"
            echo build-cache="$build_cache" >>"$GITHUB_OUTPUT"
            echo build-cache-shared="$build_cache" >>"$GITHUB_OUTPUT"
          fi

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        if: ${{ !github.event.localrun && env.IMAGE_REPOSITORY }}
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-session-name: container-build
          aws-region: ${{ vars.AWS_REGION }}
          # Identical to usage in push.yml
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # TODO: Use this instead of aws-{access,secret}, but needs proper roles & policies
          # role-to-assume: ${{ vars.AWS_ECR_ROLE }}

      - name: Log in to Amazon ECR
        if: ${{ steps.aws-creds.conclusion == 'success' }}
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          # driver-opts: image=moby/buildkit:buildx-stable-1
          driver-opts: |
            image=${{vars.AWS_ECR_REPO_BASE}}/moby/buildkit:buildx-stable-1
          install: true
          use: true

      - name: Generate image metadata
        id: meta
        # This step requires a valid GitHub token to query the API for e.g. description of repository
        if: ${{ !github.event.localrun }}
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.inputs.outputs.image-repository }}
          tags: |
            # Edge without prefix should only be used on `main`, so as not to conflict with type=sha
            # type=edge
            type=edge,prefix=edge-
            # SemVer by tag (e.g. v1.2.3)
            type=semver,pattern={{version}}
            type=pep440,pattern={{version}}
            # PR branch/name
            type=ref,event=branch
            type=ref,event=push
            type=ref,event=pull_request
            type=ref,event=workflow_dispatch
            # Git SHA
            type=sha,format=short,prefix=
            type=sha,format=long,prefix=
            # The final sha for the merge commit
            # mcgh: Merge Commit GitHub
            type=raw,value=mcgh-${{ github.event.pull_request.merge_commit_sha }}

      - name: Docker build/cache dependencies
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/ci/Dockerfile
          push: false
          target: deps
          build-args: |
            NODE_IMAGE_TAG=${{ needs.prepare.outputs.node-image-tag }}
            PLAYWRIGHT_IMAGE_TAG=${{ needs.prepare.outputs.playwright-image-tag }}
          cache-from: ${{ steps.inputs.outputs.build-cache-shared }}
          cache-to: ${{ steps.inputs.outputs.build-cache-shared }},mode=max

      - name: Docker build/cache output base
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/ci/Dockerfile
          push: false
          target: output-base-full
          build-args: |
            NODE_IMAGE_TAG=${{ needs.prepare.outputs.node-image-tag }}
            PLAYWRIGHT_IMAGE_TAG=${{ needs.prepare.outputs.playwright-image-tag }}
          cache-from: ${{ steps.inputs.outputs.build-cache-shared }}
          cache-to: ${{ steps.inputs.outputs.build-cache-shared }},mode=max

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/ci/Dockerfile
          push: ${{ !github.event.localrun }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          target: output-${{ matrix.docker }}
          build-args: |
            NODE_IMAGE_TAG=${{ needs.prepare.outputs.node-image-tag }}
            APP=${{ matrix.project }}
            PLAYWRIGHT_IMAGE_TAG=${{ needs.prepare.outputs.playwright-image-tag }}
          # Caching final images doesn't make sense when this should only run if the project is affected (changed)
          cache-from: |
            ${{ steps.inputs.outputs.build-cache-shared }}
            ${{ steps.inputs.outputs.build-cache }}
          cache-to: ${{ steps.inputs.outputs.build-cache }},mode=min
