name: 'Prep Dependencies'
on:
  workflow_call:
    outputs:
      TEST_CHUNKS:
        value: ${{ jobs.prepare.outputs.test_chunks }}
      E2E_CHUNKS:
        value: ${{ jobs.prepare.outputs.e2e_chunks }}
      E2E_BUILD_ID:
        value: ${{ jobs.prepare.outputs.build_iD }}
      BUILD_CHUNKS:
        value: ${{ jobs.prepare.outputs.build_chunks }}
      NX_BASE:
        value: ${{ jobs.prepare.outputs.nx_base }}
env:
  COMPOSE_HTTP_TIMEOUT: 180
  CHUNK_SIZE: ${{ vars.CHUNK_SIZE || 3 }}
  DISABLE_GROUPING: ${{ vars.DISABLE_GROUPING || false }}
  DISABLE_CHUNKS: ${{ vars.DISABLE_CHUNKS || false }}
  DISABLE_PROBLEMATIC: ${{ vars.DISABLE_PROBLEMATIC || false }}
  MAX_JOBS: ${{ vars.MAX_JOBS || 2 }}
  NX_PARALLEL: ${{ vars.NX_PARALLEL || 2 }}
  NX_MAX_PARALLEL: ${{ vars.NX_MAX_PARALLEL || 4 }}
  AFFECTED_ALL: ${{ secrets.AFFECTED_ALL }}
  SERVERSIDE_FEATURES_ON: ''
  DOCKER_REGISTRY: 821090935708.dkr.ecr.eu-west-1.amazonaws.com
  GENERATED_FILES: ${{ github.sha }}.tar.gz

jobs:
  install:
    outputs:
      TEST_CHUNKS: ${{ steps.build_info.outputs.test_chunks }}
      E2E_CHUNKS: ${{ steps.build_info.outputs.e2e_chunks }}
      E2E_BUILD_ID: ${{ steps.build_info.outputs.build_iD }}
      BUILD_CHUNKS: ${{ steps.build_info.outputs.build_chunks }}
      NX_BASE: ${{ steps.build_info.outputs.nx_base }}
    runs-on: arc-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Yarn
        shell: bash
        run: |
          corepack enable
          corepack prepare --activate
          yarn --version

      - name: Link pre-installed dependencies
        shell: bash
        run: |
          rm -rf node_modules
          ln -s /home/runner/dependencies/node_modules .
          ln -s /home/runner/dependencies/.yarn/cache .yarn/
          ln -s /home/runner/dependencies/.yarn/install-state.gz .yarn/
          echo "NODE_PATH=/home/runner/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV

      - uses: ./.github/actions/prep-deps

      - name: Derive appropriate SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Set base/head sha output
        id: export-sha
        shell: bash
        run: |
          echo NX_HEAD="${{ env.NX_HEAD }}" >> "$GITHUB_OUTPUT"
          echo NX_BASE="${{ env.NX_BASE }}" >> "$GITHUB_OUTPUT"

          echo "Current base SHA is ${{ env.NX_BASE }} and head SHA is ${{ env.NX_HEAD }}"
          echo "{\"base_sha\": \"${{ env.NX_BASE }}\", \"head_sha\":\"${{ env.NX_HEAD }}\"}" > event.json

      - name: Git bot config
        id: git-bot-config
        run: |
          git config --global user.email "ci@island.is"
          git config --global user.name "CI Bot"

      # This is to increase the retention days for our GitHub Actions run events
      # See this for more information:
      # https://github.blog/changelog/2020-10-08-github-actions-ability-to-change-retention-days-for-artifacts-and-logs/
      - name: Keep PR run event
        uses: actions/upload-artifact@b18b1d32f3f31abcdc29dee3f2484801fe7822f4

        # Don't run this step locally
        if: ${{ !github.event.localrun }}
        with:
          name: pr-event
          path: event.json
          retention-days: 90
          include-hidden-files: true
          if-no-files-found: error

      - name: Gather branch info
        id: build_info
        shell: bash
        run: |
          echo "TEST_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh test)}"
          if [[ "$TEST_CHUNKS" != "[]" ]]; then
            echo TEST_CHUNKS="{\"projects\":$TEST_CHUNKS}" >> "$GITHUB_OUTPUT"
          fi

          echo "BUILD_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh build)}"
          if [[ "$BUILD_CHUNKS" != "[]" ]]; then
            echo BUILD_CHUNKS="{\"projects\":$BUILD_CHUNKS}" >> "$GITHUB_OUTPUT"
          fi


          echo "E2E_CHUNKS={\"projects\":$(./scripts/ci/generate-chunks.sh e2e-ci)}"
          if [[ "$E2E_CHUNKS" != "[]" ]]; then
            echo E2E_CHUNKS="{\"projects\":$E2E_CHUNKS}" >> "$GITHUB_OUTPUT"
          fi
          echo BUILD_ID="$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER-$(uuidgen)" >> "$GITHUB_OUTPUT"
