name: 🧪 Kaniko build with dynamic Dockerfile

on:
  pull_request:

concurrency:
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value
  group: kaniko-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: arc-shared
    container:
      image: gcr.io/kaniko-project/executor:v1.23.2-debug # the kaniko image
    permissions:
      contents: read
      packages: write
      actions: write
      attestations: write
      id-token: write

    steps:
      - name: Build and push container test
        run: |
          set -x
          AUTH=$(echo -n ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} | base64)
          echo "{\"auths\": {\"ghcr.io\": {\"auth\": \"${AUTH}\"}}}" > /kaniko/.docker/config.json

          cat "${{ github.workspace }}/hack/Dockerfile"

          /kaniko/executor \
            --dockerfile="./hack/Dockerfile" \
            --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}"  \
            --destination="ghcr.io/island-is/island.is/kaniko-build:test"

        env: # authenticate to ACR via Azure Service Principal
          GIT_USERNAME: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
