name: 🧪 Kaniko build with dynamic Dockerfile

on:
  pull_request:

concurrency:
  group: kaniko-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

jobs:
  build-kaniko:
    runs-on: arc-shared
    container:
      image: gcr.io/kaniko-project/executor:debug

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare Dockerfile
        run: |
          mkdir -p ./images
          cat > ./images/kaniko-build-test.Dockerfile << 'EOF'
          FROM cgr.dev/chainguard/wolfi-base:latest
          RUN apk add --no-cache \
            git \
            jq \
            wget
          CMD ["echo", "hello world"]
          EOF
          echo "Dockerfile created at ./images/kaniko-build-test.Dockerfile"
          cat ./images/kaniko-build-test.Dockerfile

      - name: Build with Kaniko
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          /kaniko/executor \
            --dockerfile="./images/kaniko-build-test.Dockerfile" \
            --context="${{ github.workspace }}" \
            --destination="${ECR_REGISTRY}/docker-cache:levy-test" \
            --image-name-with-digest-file=/workspace/image-digest.txt
