name: Validate code in the merge queue (post merge)

on:
  workflow_dispatch: {}
  merge_group:
  pull_request:
    types:
      - synchronize
      - labeled
defaults:
  run:
    shell: bash -euxo pipefail {0}

concurrency:
  group: merge-queue-post-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  COMPOSE_HTTP_TIMEOUT: 180
  SKIP_GENERATED_CACHE: ${{ contains(github.event.pull_request.labels.*.name, 'skip-generated-cache') }}
  NX_AFFECTED_ALL: ${{ contains(github.event.pull_request.labels.*.name, 'nx-affected-all') }}
  CHUNK_SIZE: ${{ vars.CHUNK_SIZE || 3 }}
  DISABLE_GROUPING: ${{ vars.DISABLE_GROUPING || false }}
  DISABLE_CHUNKS: ${{ vars.DISABLE_CHUNKS || false }}
  DISABLE_PROBLEMATIC: ${{ vars.DISABLE_PROBLEMATIC || false }}
  MAX_JOBS: ${{ vars.MAX_JOBS || 2 }}
  NX_PARALLEL: ${{ vars.NX_PARALLEL || 2 }}
  NX_MAX_PARALLEL: ${{ vars.NX_MAX_PARALLEL || 4 }}

jobs:
  prepare:
    if: ${{ github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'ci debug') }}
    runs-on: arc-runners
    outputs:
      affected: ${{ steps.affected.outputs.build-chunks }}
      nx: ${{ steps.build-args.outputs.nx }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - name: Setup yarn
        run: corepack enable
      - name: Get cache
        id: get_cache
        uses: ./.github/actions/get-cache
        with:
          github-token: ${{ github.token }}
          enable-cache: node_modules,${{ github.event.localrun && 'generated-files' || '' }}
      - name: Derive appropriate SHAs
        uses: nrwl/nx-set-shas@v4
      - name: Find affected projects
        id: affected
        env:
          BASE: ${{ env.NX_BASE }}
          HEAD: ${{ env.NX_HEAD }}
        run: |
          chunks="build-chunks={\"projects\":$(./scripts/ci/generate-chunks.sh build)}"
          echo "$chunks" >>"$GITHUB_OUTPUT"
          echo "nx={\"parallel\":${{ env.NX_PARALLEL }},\"max-parallel\":${{ env.NX_MAX_PARALLEL }}}"

  docker-build:
    uses: ./.github/workflows/docker.yml
    needs:
      - prepare
    with:
      projects: ${{ needs.prepare.outputs.affected }}
      build-args: |
        --build-arg="NX_PARALLEL=${{ needs.prepare.outputs.nx.parallel }}"
        --build-arg="NX_MAX_PARALLEL=${{ needs.prepare.outputs.nx.max-parallel }}"
        --build-arg="NX_TASKS_RUNNER=ci"

  success:
    runs-on: arc-runners
    # if: ${{ !cancelled() }}
    needs:
      - docker-build
      # - prepare
      # - tests
      # - e2e
      # - build
    env:
      needs_results: ${{ needs.*.result }}
      needs: ${{ needs }}
    steps:
      - run: |
          set -x
          echo "$needs_results"
          echo "$needs" | jq -ne '[.[] | select(.result != "success") ] | length == 0'
      - name: Check docker-build success
        run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
      - name: Announce success
        run: echo "Build is successful"
      # - name: Check prepare success
      #   run: '[[ ${{ needs.prepare.result }} == "success" ]] || exit 1'
      # - name: Check tests success
      #   run: '[[ ${{ needs.tests.result }} != "failure" ]] || exit 1'
      # - name: Check e2e success
      #   run: '[[ ${{ needs.e2e.result }} != "failure" ]] || exit 1'
      # - name: Check build success
      #   run: '[[ ${{ needs.build.result }} != "failure" ]] || exit 1'

  # Remove this as a required status check and switch to something more meaningful
  codeowners-check:
    if: false
    name: Lint CODEOWNERS
    runs-on: arc-runners
    env:
      CHECK: 'false'
    steps:
      - name: Codeowners validation
        run: |
          exit 0
