name: Validate code in the merge queue

on:
  push:
  pull_request:
    types:
      - closed
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    outputs:
          READY_FOR_MERGE: ${{ steps.validate-pr.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display info
        run: |
          echo "Hallo Merge Queue"
          pwd
          tree -a -I '.git'
          git status
      - name: Run slow CI (emulated by a long sleep)
        run: |
          sleep 300
      - name: Ready for merge
        run: echo "READY_FOR_MERGE=true" >> $GITHUB_OUTPUT

