name: Validate code in the merge queue

on:
  merge_group:

jobs:
  check-ready-for-merge-queue:
    name: Ready for mergequeue
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Display info
        run: |
          echo "Hallo Merge Queue"
          pwd
          tree -a -I '.git'
          git status
      - name: Run slow CI (emulated by a long sleep)
        run: |
          sleep 300
