name: Release created

on:
  pull_request:
  
jobs:
    mq:
        runs-on: arc-runners
        steps:
        - run: |
            export GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF/refs\/heads\//}}"
            echo "New release branch created: $GIT_BRANCH"
            curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/merge-queue.yml/dispatches \
            -d "{\"ref\":\"$GIT_BRANCH\"}"

    