name: Release created

on:
  pull_request:
  push:
    branches:
      - 'releases/**'
      - 'on-release-create'

jobs:
    mq:
        if: github.event.created
        runs-on: arc-runners
        steps:
        - run: |
            export GIT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF/refs\/heads\//}}"
            curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workflow-b.yml/dispatches \
            -d '{"ref":"${GIT_BRANCH}"}'

    