name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ec2-runners
    container: 
      image: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/actions-runner:latest
      credentials:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: amannn/action-semantic-pull-request@v4.2.0
        with:
          types: |
            feat
            infra
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
