name: Check PR title
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ec2-runners
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        with:
          types: |
            feat
            infra
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
