name: PR close

on:
  push:
    branches:
      - ci/cherry-pick-unicorn
  # pull_request:
  #   types:
  #     - closed

defaults:
  run:
    shell: bash

jobs:
  check-unicorn:
    name: Is this a unicorn PR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      IS_UNICORN: ${{ steps.unicorn_affected.outputs.IS_UNICORN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Find Latest Release Branch
        if: ${{ steps.unicorn_affected.outputs.IS_UNICORN == 'true' }}
        id: get_latest_release
        run: |
          test="hallo"
          test=$(git branch)
          echo $test
          test=$(git branch -a)
          echo $test
          test=$(git branch -r)
          echo $test
          node scripts/ci/get-last-release.mjs $(git branch -r)

