name: PR lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint PR title
    runs-on: arc-runners
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            infra
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-changed-files:
    name: Lint Changed Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup yarn
        uses: ./.github/actions/setup-yarn
        with:
          RUNS_ON_S3_BUCKET_CACHE: ${{ secrets.S3_DOCKER_CACHE_BUCKET }}

      - name: Get changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.ref }})" >> "$GITHUB_ENV"

      - name: Run lint on changed files
        if: ${{ env.CHANGED_FILES != '' }}
        run: yarn nx affected -t lint --lintFilePatterns=$(echo ${CHANGED_FILES}) --verbose
