name: 'Staleness'
on:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC
  workflow_dispatch: # Allow manual run

jobs:
  stale:
    runs-on: arc-runners
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 7
          days-before-close: -1 # Never auto-close
          only-pr-labels: deploy-feature
          remove-labels: deploy-feature
          stale-pr-message: |
            This PR has been inactive for over a week. The `deploy-feature` label has been removed. Re-add the label to re-enable automatic deploy previews.
          operations-per-run: 100
