name: Build and deploy

on: 
    workflow_dispatch: {}
    pull_request:
    merge_group:

concurrency:
  group: build-deploy-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    test:
        runs-on: arc-shared
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 1
                clean: true
                sparse-checkout: |
                    .github
                sparse-checkout-cone-mode: true
            - name: Test
              uses: ./.github/workflows/dagger.yml
              with:
                  function: test
                  

