name: Build and deploy

on: 
    workflow_dispatch: {}
    pull_request:
    merge_group:

concurrency:
  group: build-deploy-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    test:
        uses: ./.github/workflows/dagger.yml
        secrets: inherit
        with:
            function: prepare
            sha: ${{ github.sha }}
                  

