name: CI/CD pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/unicorn-app-pipeline' #temp for debugging and testing

jobs:
  check-unicorn:
    needs:
      - prepare
    name: Check if app is on unicorn track
    runs-on: ubuntu-latest

    outputs:
      IS_UNICORN: ${{ steps.unicorn-affected.outputs.IS_UNICORN }}
    steps:
      - name: Check unicorn affected
        id: unicorn-affected
        run: |
          set -euo pipefail
          ls
          yarn install
          UNICORN=$(yarn is-unicorn)
          if [ "$UNICORN" = 'true' ]; then
              echo "unicorn is detected"
              echo IS_UNICORN=true >> "$GITHUB_OUTPUT"
          else
              echo "No unicorn"
              echo IS_UNICORN=false >> "$GITHUB_OUTPUT"
          fi

  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: yarn install
        run: yarn install
