name: CI/CD pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/unicorn-app-pipeline' #temp for debugging and testing

jobs:
  check-unicorn:
    needs:
      - prepare
    name: Check if app is on unicorn track
    runs-on: ec2-runners
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    timeout-minutes: 35

    outputs:
      IS_UNICORN: ${{ steps.unicorn-affected.outputs.IS_UNICORN }}
    steps:
      - name: Check unicorn affected
        id: unicorn-affected
        run: |
          UNICORN=$(yarn is-unicorn)
          if [ "$UNICORN" = 'true' ]; then
              echo "unicorn is detected"
              echo IS_UNICORN=true >> "$GITHUB_OUTPUT"
          else
              echo "No unicorn"
              echo IS_UNICORN=false >> "$GITHUB_OUTPUT"
          fi

  prepare:
    runs-on: ec2-runners
    container:
      image: public.ecr.aws/m3u4c4h9/island-is/actions-runner-public:latest
    timeout-minutes: 35
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Setup yarn
        run: corepack enable

      - name: Get cache
        id: get-cache
        uses: ./.github/actions/get-cache
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-cache: 'node_modules,generated-files'

