on:
  push: {}
defaults:
  run:
    shell: bash

jobs:
  update-helm-values-repository:
    runs-on: arc-runners
    timeout-minutes: 90
    steps:
      - name: Checkout out island.is repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Update helm-values repository
        uses: ./.github/actions/update-helm-values
        with:
          files: 'charts/islandis-services/air-discount-scheme-backend/values.dev.yaml,charts/islandis-services/air-discount-scheme-web/values.dev.yaml'
          gh_token_pat: ${{ secrets.GH_HELM_VALUES_PAT }}
