name: 'Setup yarn'
description: 'Yarn setup and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Yarn
      shell: bash
      run: |
        corepack enable
        corepack prepare --activate
        yarn --version

    - name: Link pre-installed dependencies
      shell: bash
      run: |
        rm -rf node_modules
        ln -s /home/runner/dependencies/node_modules .
        ln -s /home/runner/dependencies/.yarn/cache .yarn/
        ln -s /home/runner/dependencies/.yarn/install-state.gz .yarn/
        echo "NODE_PATH=/home/runner/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV
