name: 'Setup yarn'
description: 'Yarn setup and install dependencies. This is our authoritative place to set up Yarn, including setting cache locations etc.'

runs:
  using: 'composite'
  steps:
    - name: Compare yarn.lock files
      shell: bash
      id: compare_yarn_lock
      run: |
        current=$(sha256sum yarn.lock | awk '{print $1}')
        bundled=$(sha256sum /home/runner/dependencies/yarn.lock | awk '{print $1}') || echo "Failed reading bundled yarn.lock, ignoring..."
        skip_install=$([ "$current" = "$bundled" ] && echo true || echo false)
        echo "Current hash: $current"
        echo "Bundled hash: $bundled"
        echo "Will skip running 'yarn install' step: $skip_install"
        echo "skip_install=$skip_install" >> $GITHUB_OUTPUT

    - name: Setup Yarn
      shell: bash
      env:
        COREPACK_CACHE: ${{ format('{0}/corepack.tgz', env.COREPACK_HOME) }}
      run: |
        # Set shims for e.g. `node` and `yarn`
        corepack enable
        # Use corepack cache if it exists (see https://github.com/nodejs/corepack?tab=readme-ov-file#offline-workflow)
        [[ -e "${COREPACK_CACHE}" ]] && corepack install -g yarn --cache-only "${COREPACK_CACHE}" || corepack install -g yarn
        # Verify yarn is available, and see version
        yarn --version

    - name: Run yarn install if yarn.lock changed
      shell: bash
      if: ${{ steps.compare_yarn_lock.outputs.skip_install == 'false' }}
      run: |
        yarn install --immutable
        (
          cp -rf ./node_modules /home/runner/dependencies/node_modules
          cp -rf ./.yarn /home/runner/dependencies/.yarn
          cp -rf ./yarn.lock /home/runner/dependencies/yarn.lock
          cp -rf ./package.json /home/runner/dependencies/package.json
        ) || echo "Failed copying back to dependencies

    - name: Link pre-installed dependencies
      if: ${{ steps.compare_yarn_lock.outputs.skip_install == 'true' }}
      shell: bash
      run: |
        rm -rf node_modules
        ln -s /home/runner/dependencies/node_modules .
        ln -s /home/runner/dependencies/.yarn/cache .yarn/
        # ln -s /home/runner/dependencies/.yarn/install-state.gz .yarn/
        echo "NODE_PATH=/home/runner/dependencies/node_modules:$NODE_PATH" >> $GITHUB_ENV
