{
  "judicial-system-backend": {
    "serviceDef": {
      "liveness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "readiness": {
        "path": "/liveness",
        "timeoutSeconds": 3,
        "initialDelaySeconds": 3
      },
      "env": {
        "DOKOBIT_URL": {
          "dev": "https://developers.dokobit.com",
          "staging": "https://developers.dokobit.com",
          "prod": "https://ws.dokobit.com"
        },
        "EMAIL_REGION": "eu-west-1",
        "S3_REGION": "eu-west-1",
        "S3_BUCKET": {
          "dev": "island-is-dev-upload-judicial-system",
          "staging": "island-is-staging-upload-judicial-system",
          "prod": "island-is-prod-upload-judicial-system"
        },
        "S3_TIME_TO_LIVE_POST": "15",
        "S3_TIME_TO_LIVE_GET": "5",
        "CONTENTFUL_HOST": {
          "dev": "preview.contentful.com",
          "staging": "cdn.contentful.com",
          "prod": "cdn.contentful.com"
        },
        "CONTENTFUL_ENVIRONMENT": {
          "dev": "test",
          "staging": "test",
          "prod": "master"
        },
        "CLIENT_URL": {
          "prod": "https://rettarvorslugatt.island.is"
        },
        "SQS_QUEUE_NAME": "sqs-judicial-system",
        "SQS_DEAD_LETTER_QUEUE_NAME": "sqs-judicial-system-dlq",
        "SQS_REGION": "eu-west-1",
        "BLOCKED_API_INTEGRATION": {
          "dev": "",
          "staging": "COURT,POLICE_CASE",
          "prod": ""
        },
        "NOVA_ACCEPT_UNAUTHORIZED": {
          "dev": "true",
          "staging": "false",
          "prod": "false"
        },
        "USE_MICROSOFT_GRAPH_API_FOR_COURT_ROBOT": {
          "dev": "false",
          "staging": "true",
          "prod": "true"
        }
      },
      "features": {},
      "name": "judicial-system-backend",
      "grantNamespaces": [],
      "grantNamespacesEnabled": false,
      "secrets": {
        "CONFIGCAT_SDK_KEY": "/k8s/configcat/CONFIGCAT_SDK_KEY",
        "NOVA_URL": "/k8s/judicial-system/NOVA_URL",
        "NOVA_USERNAME": "/k8s/judicial-system/NOVA_USERNAME",
        "NOVA_PASSWORD": "/k8s/judicial-system/NOVA_PASSWORD",
        "COURTS_MOBILE_NUMBERS": "/k8s/judicial-system/COURTS_MOBILE_NUMBERS",
        "COURTS_ASSISTANT_MOBILE_NUMBERS": "/k8s/judicial-system/COURTS_ASSISTANT_MOBILE_NUMBERS",
        "COURTS_EMAILS": "/k8s/judicial-system/COURTS_EMAILS",
        "DOKOBIT_ACCESS_TOKEN": "/k8s/judicial-system/DOKOBIT_ACCESS_TOKEN",
        "EMAIL_FROM": "/k8s/judicial-system/EMAIL_FROM",
        "EMAIL_FROM_NAME": "/k8s/judicial-system/EMAIL_FROM_NAME",
        "EMAIL_REPLY_TO": "/k8s/judicial-system/EMAIL_REPLY_TO",
        "EMAIL_REPLY_TO_NAME": "/k8s/judicial-system/EMAIL_REPLY_TO_NAME",
        "PRISON_EMAIL": "/k8s/judicial-system/PRISON_EMAIL",
        "PRISON_ADMIN_EMAIL": "/k8s/judicial-system/PRISON_ADMIN_EMAIL",
        "AUTH_JWT_SECRET": "/k8s/judicial-system/AUTH_JWT_SECRET",
        "ADMIN_USERS": "/k8s/judicial-system/ADMIN_USERS",
        "BACKEND_ACCESS_TOKEN": "/k8s/judicial-system/BACKEND_ACCESS_TOKEN",
        "CONTENTFUL_ACCESS_TOKEN": "/k8s/judicial-system/CONTENTFUL_ACCESS_TOKEN",
        "EVENT_URL": "/k8s/judicial-system/EVENT_URL",
        "ERROR_EVENT_URL": "/k8s/judicial-system/ERROR_EVENT_URL",
        "ARCHIVE_ENCRYPTION_KEY": "/k8s/judicial-system/ARCHIVE_ENCRYPTION_KEY",
        "COURT_ROBOT_CLIENT_ID": "/k8s/judicial-system/COURT_ROBOT_CLIENT_ID",
        "COURT_ROBOT_TENANT_ID": "/k8s/judicial-system/COURT_ROBOT_TENANT_ID",
        "COURT_ROBOT_CLIENT_SECRET": "/k8s/judicial-system/COURT_ROBOT_CLIENT_SECRET",
        "COURT_ROBOT_USER": "/k8s/judicial-system/COURT_ROBOT_USER",
        "COURT_ROBOT_EMAIL": "/k8s/judicial-system/COURT_ROBOT_EMAIL"
      },
      "ingress": {},
      "namespace": "judicial-system",
      "serviceAccountEnabled": true,
      "securityContext": {
        "privileged": false,
        "allowPrivilegeEscalation": false
      },
      "resources": {
        "requests": {
          "cpu": "100m",
          "memory": "512Mi"
        },
        "limits": {
          "cpu": "400m",
          "memory": "1024Mi"
        }
      },
      "xroadConfig": [
        {
          "config": {
            "env": {
              "XROAD_BASE_PATH": {
                "prod": "http://securityserver.island.is"
              },
              "XROAD_BASE_PATH_WITH_ENV": {
                "staging": "http://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "http://securityserver.island.is/r1/IS"
              },
              "XROAD_TLS_BASE_PATH": {
                "dev": "https://securityserver.dev01.devland.is",
                "staging": "https://securityserver.staging01.devland.is",
                "prod": "https://securityserver.island.is"
              },
              "XROAD_TLS_BASE_PATH_WITH_ENV": {
                "dev": "https://securityserver.dev01.devland.is/r1/IS-DEV",
                "staging": "https://securityserver.staging01.devland.is/r1/IS-TEST",
                "prod": "https://securityserver.island.is/r1/IS"
              }
            }
          }
        },
        {
          "config": {
            "env": {
              "XROAD_CLIENT_ID": {
                "dev": "IS-DEV/GOV/10014/Rettarvorslugatt-Client",
                "staging": "IS-TEST/GOV/5804170510/Rettarvorslugatt-Client",
                "prod": "IS/GOV/5804170510/Rettarvorslugatt-Client"
              },
              "XROAD_COURT_MEMBER_CODE": {
                "dev": "10019",
                "staging": "4707171140",
                "prod": "4707171140"
              },
              "XROAD_POLICE_MEMBER_CODE": {
                "dev": "10005",
                "staging": "5309672079",
                "prod": "5309672079"
              },
              "XROAD_COURT_API_PATH": "/Domstolasyslan/JusticePortal-v1",
              "XROAD_POLICE_API_PATH": "/Logreglan-Private/rettarvarsla-v1"
            },
            "secrets": {
              "XROAD_CLIENT_CERT": "/k8s/judicial-system/XROAD_CLIENT_CERT",
              "XROAD_CLIENT_KEY": "/k8s/judicial-system/XROAD_CLIENT_KEY",
              "XROAD_CLIENT_PEM": "/k8s/judicial-system/XROAD_CLIENT_PEM",
              "XROAD_COURTS_CREDENTIALS": "/k8s/judicial-system/COURTS_CREDENTIALS",
              "XROAD_POLICE_API_KEY": "/k8s/judicial-system/XROAD_POLICE_API_KEY"
            }
          }
        }
      ],
      "files": [],
      "volumes": [],
      "accountName": "judicial-system-backend",
      "postgres": {
        "name": "judicial_system",
        "username": "judicial_system",
        "passwordSecret": "/k8s/judicial-system/DB_PASSWORD"
      },
      "initContainers": {
        "envs": {},
        "secrets": {},
        "features": {},
        "containers": [
          {
            "name": "migrations",
            "command": "npx",
            "args": [
              "sequelize-cli",
              "db:migrate"
            ]
          }
        ],
        "postgres": {
          "name": "judicial_system",
          "username": "judicial_system",
          "passwordSecret": "/k8s/judicial-system/DB_PASSWORD"
        }
      },
      "replicaCount": {
        "min": 2,
        "max": 10,
        "default": 2
      }
    }
  }
}